export interface DialogueLine {
  speaker: 'A' | 'B';
  text: string;
  cn: string;
}

export interface Dialogue {
  title: string;
  icon: string;
  color: string;
  level: 1 | 2 | 3 | 4 | 5;
  scenario: DialogueLine[];
}

export const dialogues: Dialogue[] = [
  // === Level 1: 基础问候与简单交流 (1-40) ===
  {
    title: '打招呼',
    icon: '👋',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hello! How are you today?', cn: '你好！你今天怎么样？' },
      { speaker: 'B', text: 'Hello! I am fine, thank you. And you?', cn: '你好！我很好，谢谢。你呢？' },
      { speaker: 'A', text: 'I am fine too. What is your name?', cn: '我也很好。你叫什么名字？' },
      { speaker: 'B', text: 'My name is Tom. What about you?', cn: '我叫汤姆。你呢？' },
      { speaker: 'A', text: 'I am Amy. Nice to meet you!', cn: '我是艾米。很高兴认识你！' },
      { speaker: 'B', text: 'Nice to meet you too! How old are you?', cn: '我也很高兴认识你！你多大了？' },
      { speaker: 'A', text: 'I am nine years old. What about you?', cn: '我九岁。你呢？' },
      { speaker: 'B', text: 'I am ten years old. Goodbye!', cn: '我十岁。再见！' },
      { speaker: 'A', text: 'Goodbye! See you tomorrow!', cn: '再见！明天见！' },
      { speaker: 'B', text: 'See you tomorrow!', cn: '明天见！' },
    ]
  },
  {
    title: '问好',
    icon: '☀️',
    color: 'bg-yellow-100 dark:bg-yellow-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Good morning, mom!', cn: '早上好，妈妈！' },
      { speaker: 'B', text: 'Good morning, dear! Did you sleep well?', cn: '早上好，亲爱的！睡得好吗？' },
      { speaker: 'A', text: 'Yes, I slept very well. Thank you.', cn: '是的，我睡得很好。谢谢。' },
      { speaker: 'B', text: 'That is good. What do you want for breakfast?', cn: '那很好。早餐想吃什么？' },
      { speaker: 'A', text: 'I want milk and bread, please.', cn: '我要牛奶和面包，谢谢。' },
      { speaker: 'B', text: 'Okay, here is your breakfast.', cn: '好的，这是你的早餐。' },
      { speaker: 'A', text: 'Thank you, mom. It smells good!', cn: '谢谢妈妈。闻起来真香！' },
      { speaker: 'B', text: 'Eat slowly. You have school today.', cn: '慢慢吃。你今天要上学。' },
      { speaker: 'A', text: 'I know. I will be quick.', cn: '我知道。我会很快。' },
      { speaker: 'B', text: 'Good. Have a great day at school!', cn: '好的。祝你在学校过得愉快！' },
    ]
  },
  {
    title: '道别',
    icon: '👋',
    color: 'bg-pink-100 dark:bg-pink-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hello, my friend!', cn: '你好，我的朋友！' },
      { speaker: 'B', text: 'Hi! How are you?', cn: '嗨！你好吗？' },
      { speaker: 'A', text: 'I am good. It is getting late.', cn: '我很好。天色晚了。' },
      { speaker: 'B', text: 'Yes, it is time to go home.', cn: '是的，该回家了。' },
      { speaker: 'A', text: 'I need to go now. Goodbye!', cn: '我现在要走了。再见！' },
      { speaker: 'B', text: 'Goodbye! See you tomorrow!', cn: '再见！明天见！' },
      { speaker: 'A', text: 'Take care of yourself!', cn: '保重！' },
      { speaker: 'B', text: 'You too! Have a good night!', cn: '你也是！晚安！' },
      { speaker: 'A', text: 'Thank you. You too!', cn: '谢谢。你也是！' },
      { speaker: 'B', text: 'Bye!', cn: '再见！' },
    ]
  },
  {
    title: '道晚安',
    icon: '🌙',
    color: 'bg-indigo-100 dark:bg-indigo-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Mom, I am very tired.', cn: '妈妈，我很累。' },
      { speaker: 'B', text: 'Oh, my dear. It is bedtime then.', cn: '哦，亲爱的。那就该睡觉了。' },
      { speaker: 'A', text: 'Yes, I want to sleep now.', cn: '是的，我想现在睡觉。' },
      { speaker: 'B', text: 'Let me help you get ready for bed.', cn: '让我帮你准备睡觉。' },
      { speaker: 'A', text: 'Thank you, mom. Good night!', cn: '谢谢妈妈。晚安！' },
      { speaker: 'B', text: 'Good night, my love. Sweet dreams!', cn: '晚安，我的爱。做个好梦！' },
      { speaker: 'A', text: 'I will dream about you, mom!', cn: '我会梦见你的，妈妈！' },
      { speaker: 'B', text: 'That is sweet. Sleep well!', cn: '那太贴心了。睡个好觉！' },
      { speaker: 'A', text: 'I love you, mom!', cn: '我爱你，妈妈！' },
      { speaker: 'B', text: 'I love you too! Good night!', cn: '我也爱你！晚安！' },
    ]
  },
  {
    title: '谢谢',
    icon: '🙏',
    color: 'bg-green-100 dark:bg-green-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Can you help me with my bag?', cn: '你能帮我拿包吗？' },
      { speaker: 'B', text: 'Sure! Here, let me carry it for you.', cn: '当然！这里，让我帮你拿。' },
      { speaker: 'A', text: 'Thank you very much!', cn: '非常感谢！' },
      { speaker: 'B', text: 'You are welcome! Is it heavy?', cn: '不客气！重吗？' },
      { speaker: 'A', text: 'A little. Thank you for helping.', cn: '有点。谢谢你的帮助。' },
      { speaker: 'B', text: 'No problem. I am happy to help.', cn: '没问题。我很乐意帮忙。' },
      { speaker: 'A', text: 'You are very kind. Thank you again!', cn: '你真好。再次感谢！' },
      { speaker: 'B', text: 'Anytime. Do you need anything else?', cn: '随时。还需要别的吗？' },
      { speaker: 'A', text: 'No, that is all. Thank you!', cn: '不需要了，就这些。谢谢！' },
      { speaker: 'B', text: 'You are welcome! Have a nice day!', cn: '不客气！祝你今天愉快！' },
    ]
  },
  {
    title: '对不起',
    icon: '😊',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Oh no! I broke your cup.', cn: '哦不！我打破了你的杯子。' },
      { speaker: 'B', text: 'That is okay. Accidents happen.', cn: '没关系。意外难免。' },
      { speaker: 'A', text: 'I am very sorry. I will buy you a new one.', cn: '我非常抱歉。我会给你买一个新的。' },
      { speaker: 'B', text: 'Don\'t worry. It is just a cup.', cn: '别担心。只是一个杯子而已。' },
      { speaker: 'A', text: 'But I feel bad about it. I am sorry.', cn: '但我心里过意不去。对不起。' },
      { speaker: 'B', text: 'I forgive you. You are my best friend.', cn: '我原谅你。你是我最好的朋友。' },
      { speaker: 'A', text: 'Thank you for understanding. I am sorry.', cn: '谢谢你的理解。对不起。' },
      { speaker: 'B', text: 'It is okay. Let\'s clean it up together.', cn: '没事。我们一起清理吧。' },
      { speaker: 'A', text: 'Yes. I will help clean. I am sorry.', cn: '好的。我会帮忙清理。对不起。' },
      { speaker: 'B', text: 'Stop saying sorry. Let\'s be happy!', cn: '别再说了。让我们开心点吧！' },
    ]
  },
  {
    title: '打招呼与问候',
    icon: '🤝',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hi there! Nice day, isn\'t it?', cn: '嗨！天气不错，不是吗？' },
      { speaker: 'B', text: 'Yes, it is beautiful! How are you?', cn: '是的，天气很美！你好吗？' },
      { speaker: 'A', text: 'I am great! Just finished my homework.', cn: '我很好！刚做完作业。' },
      { speaker: 'B', text: 'That is good! What homework did you do?', cn: '那很好！你做了什么作业？' },
      { speaker: 'A', text: 'Math and English. It was easy today.', cn: '数学和英语。今天很简单。' },
      { speaker: 'B', text: 'You are smart! I have homework too.', cn: '你真聪明！我也有作业。' },
      { speaker: 'A', text: 'What is your homework?', cn: '你的作业是什么？' },
      { speaker: 'B', text: 'Science. I need to study plants.', cn: '科学。我需要学习植物。' },
      { speaker: 'A', text: 'Sounds interesting! Can I help?', cn: '听起来很有趣！我能帮忙吗？' },
      { speaker: 'B', text: 'Thank you! Let\'s study together!', cn: '谢谢！我们一起学习吧！' },
    ]
  },
  {
    title: '请问名字',
    icon: '👤',
    color: 'bg-purple-100 dark:bg-purple-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hello, I am new here. What is your name?', cn: '你好，我是新来的。你叫什么名字？' },
      { speaker: 'B', text: 'Hi! Welcome! My name is Lily.', cn: '嗨！欢迎！我叫莉莉。' },
      { speaker: 'A', text: 'Nice to meet you, Lily. I am Jack.', cn: '很高兴认识你，莉莉。我是杰克。' },
      { speaker: 'B', text: 'Nice to meet you too, Jack!', cn: '我也很高兴认识你，杰克！' },
      { speaker: 'A', text: 'Do you live near here?', cn: '你住在这附近吗？' },
      { speaker: 'B', text: 'Yes, I live in that blue house.', cn: '是的，我就住在那所蓝色的房子里。' },
      { speaker: 'A', text: 'That is nice! How long have you lived here?', cn: '那真不错！你在这里住了多久？' },
      { speaker: 'B', text: 'For five years. I like this neighborhood.', cn: '五年了。我喜欢这个社区。' },
      { speaker: 'A', text: 'I just moved here yesterday.', cn: '我昨天刚搬来。' },
      { speaker: 'B', text: 'Welcome! Let me show you around!', cn: '欢迎！让我带你转转！' },
    ]
  },
  {
    title: '询问年龄',
    icon: '🎂',
    color: 'bg-red-100 dark:bg-red-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hey! Can I ask you something?', cn: '嘿！我可以问你个问题吗？' },
      { speaker: 'B', text: 'Sure! What do you want to ask?', cn: '当然！你想问什么？' },
      { speaker: 'A', text: 'How old are you?', cn: '你多大了？' },
      { speaker: 'B', text: 'I am eight years old. What about you?', cn: '我八岁。你呢？' },
      { speaker: 'A', text: 'I am eight too! We are the same age!', cn: '我也八岁！我们同岁！' },
      { speaker: 'B', text: 'That is great! When is your birthday?', cn: '太好了！你的生日是什么时候？' },
      { speaker: 'A', text: 'My birthday is in June. When is yours?', cn: '我的生日在六月。你的呢？' },
      { speaker: 'B', text: 'Mine is in May. Just one month before yours!', cn: '我的在五月。只比你早一个月！' },
      { speaker: 'A', text: 'Cool! We can have birthday parties together!', cn: '太酷了！我们可以一起过生日！' },
      { speaker: 'B', text: 'Yes! That will be so much fun!', cn: '是的！那会很有趣！' },
    ]
  },
  {
    title: '认识',
    icon: '🤝',
    color: 'bg-green-100 dark:bg-green-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hi! I saw you at the library yesterday.', cn: '嗨！我昨天在图书馆看到你。' },
      { speaker: 'B', text: 'Oh really? I was reading books there.', cn: '哦真的吗？我在那里看书。' },
      { speaker: 'A', text: 'Yes! What is your name? I am Tom.', cn: '是的！你叫什么名字？我是汤姆。' },
      { speaker: 'B', text: 'Nice to meet you, Tom. I am Sarah.', cn: '很高兴认识你，汤姆。我是莎拉。' },
      { speaker: 'A', text: 'Nice to meet you too, Sarah!', cn: '我也很高兴认识你，莎拉！' },
      { speaker: 'B', text: 'Do you like reading books?', cn: '你喜欢看书吗？' },
      { speaker: 'A', text: 'Yes, I love reading! What about you?', cn: '是的，我爱看书！你呢？' },
      { speaker: 'B', text: 'Me too! We can go to the library together!', cn: '我也是！我们可以一起去图书馆！' },
      { speaker: 'A', text: 'That sounds great! When can we go?', cn: '听起来很棒！我们什么时候去？' },
      { speaker: 'B', text: 'How about this Saturday? I am free!', cn: '这个星期六怎么样？我有空！' },
    ]
  },
  {
    title: '打招呼与天气',
    icon: '🌤️',
    color: 'bg-cyan-100 dark:bg-cyan-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hello! The sun is shining today!', cn: '你好！今天阳光明媚！' },
      { speaker: 'B', text: 'Yes! It is a beautiful sunny day!', cn: '是的！今天是个美丽的晴天！' },
      { speaker: 'A', text: 'Do you want to go to the park?', cn: '你想去公园吗？' },
      { speaker: 'B', text: 'Sure! What can we do there?', cn: '当然！我们在那里可以做什么？' },
      { speaker: 'A', text: 'We can play games and have a picnic.', cn: '我们可以玩游戏，野餐。' },
      { speaker: 'B', text: 'That sounds fun! Who should we invite?', cn: '听起来很有趣！我们应该邀请谁？' },
      { speaker: 'A', text: 'Let\'s invite our friends!', cn: '让我们邀请我们的朋友！' },
      { speaker: 'B', text: 'Great idea! I will bring snacks.', cn: '好主意！我会带零食。' },
      { speaker: 'A', text: 'I will bring drinks and games!', cn: '我会带饮料和游戏！' },
      { speaker: 'B', text: 'Perfect! Let\'s meet at the park!', cn: '完美！我们在公园见吧！' },
    ]
  },
  {
    title: '问候家人',
    icon: '👨‍👩‍👧',
    color: 'bg-rose-100 dark:bg-rose-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hello! How is your family?', cn: '你好！你家人怎么样？' },
      { speaker: 'B', text: 'They are doing well. Thank you for asking!', cn: '他们很好。谢谢你的关心！' },
      { speaker: 'A', text: 'How is your mother?', cn: '你妈妈怎么样？' },
      { speaker: 'B', text: 'She is good. She is cooking dinner now.', cn: '她很好。她现在正在做晚饭。' },
      { speaker: 'A', text: 'What is she cooking?', cn: '她在做什么？' },
      { speaker: 'B', text: 'Chicken and vegetables. It smells good!', cn: '鸡肉和蔬菜。闻起来很香！' },
      { speaker: 'A', text: 'Yummy! How about your father?', cn: '好吃！你爸爸呢？' },
      { speaker: 'B', text: 'He is at work. He will come home soon.', cn: '他在工作。他很快就会回家。' },
      { speaker: 'A', text: 'That is good. What about your siblings?', cn: '那很好。你的兄弟姐妹呢？' },
      { speaker: 'B', text: 'My brother is playing with his toys.', cn: '我弟弟在玩他的玩具。' },
    ]
  },
  {
    title: '答应邀请',
    icon: '✅',
    color: 'bg-emerald-100 dark:bg-emerald-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hi! Are you free this weekend?', cn: '嗨！这周末你有空吗？' },
      { speaker: 'B', text: 'Yes, I am free. Why do you ask?', cn: '是的，我有空。你为什么问？' },
      { speaker: 'A', text: 'Can you come to my birthday party?', cn: '你能来我的生日派对吗？' },
      { speaker: 'B', text: 'Wow! I would love to come!', cn: '哇！我很想来！' },
      { speaker: 'A', text: 'That is great! It is on Saturday at 3 pm.', cn: '太好了！星期六下午3点。' },
      { speaker: 'B', text: 'Okay! Where is the party?', cn: '好的！派对在哪里？' },
      { speaker: 'A', text: 'At my house. Do you know the address?', cn: '在我家。你知道地址吗？' },
      { speaker: 'B', text: 'Yes! I will bring a gift for you!', cn: '知道！我会给你带礼物！' },
      { speaker: 'A', text: 'Thank you! Can\'t wait to see you!', cn: '谢谢！迫不及待想见你！' },
      { speaker: 'B', text: 'Me too! See you on Saturday!', cn: '我也是！星期六见！' },
    ]
  },
  {
    title: '拒绝邀请',
    icon: '❌',
    color: 'bg-red-100 dark:bg-red-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hey! Do you want to play football now?', cn: '嘿！你现在想踢足球吗？' },
      { speaker: 'B', text: 'I would like to, but I cannot right now.', cn: '我想，但我现在不能。' },
      { speaker: 'A', text: 'Why? What are you doing?', cn: '为什么？你在做什么？' },
      { speaker: 'B', text: 'I have to finish my homework first.', cn: '我必须先完成作业。' },
      { speaker: 'A', text: 'Oh, I understand. How long will it take?', cn: '哦，我理解。要花多长时间？' },
      { speaker: 'B', text: 'About one hour. Can we play then?', cn: '大约一小时。到时候我们能玩吗？' },
      { speaker: 'A', text: 'Sure! I will wait for you.', cn: '当然！我会等你。' },
      { speaker: 'B', text: 'Thank you! I will be quick.', cn: '谢谢！我会很快的。' },
      { speaker: 'A', text: 'No problem. Text me when you are done.', cn: '没问题。完成后给我发短信。' },
      { speaker: 'B', text: 'Okay! See you in an hour!', cn: '好的！一小时后见！' },
    ]
  },
  {
    title: '邀请',
    icon: '📢',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hi! I have a great idea!', cn: '嗨！我有个好主意！' },
      { speaker: 'B', text: 'What is it? Tell me!', cn: '是什么？告诉我！' },
      { speaker: 'A', text: 'Let us watch a movie together!', cn: '让我们一起看电影吧！' },
      { speaker: 'B', text: 'That sounds fun! What movie?', cn: '听起来很有趣！什么电影？' },
      { speaker: 'A', text: 'A cartoon movie about animals.', cn: '一部关于动物的动画片。' },
      { speaker: 'B', text: 'I love cartoons! When should we watch?', cn: '我喜欢动画片！我们应该什么时候看？' },
      { speaker: 'A', text: 'How about this Saturday afternoon?', cn: '这个星期六下午怎么样？' },
      { speaker: 'B', text: 'Perfect! At my house or yours?', cn: '完美！在我家还是你家？' },
      { speaker: 'A', text: 'Let\'s watch at my house. I have popcorn!', cn: '在我家看吧。我有爆米花！' },
      { speaker: 'B', text: 'Great! I will bring snacks too!', cn: '太好了！我也会带零食！' },
    ]
  },
  {
    title: '打招呼与回应',
    icon: '💬',
    color: 'bg-violet-100 dark:bg-violet-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Good afternoon! How are you doing?', cn: '下午好！你怎么样？' },
      { speaker: 'B', text: 'Good afternoon! I am doing great!', cn: '下午好！我很好！' },
      { speaker: 'A', text: 'What are you doing this afternoon?', cn: '今天下午你在做什么？' },
      { speaker: 'B', text: 'I am playing with my friends.', cn: '我和朋友一起玩。' },
      { speaker: 'A', text: 'That sounds fun! What are you playing?', cn: '听起来很有趣！你们在玩什么？' },
      { speaker: 'B', text: 'We are playing hide and seek.', cn: '我们在玩捉迷藏。' },
      { speaker: 'A', text: 'Can I play with you?', cn: '我可以和你们一起玩吗？' },
      { speaker: 'B', text: 'Of course! The more, the better!', cn: '当然！人多越好！' },
      { speaker: 'A', text: 'Thank you! Let\'s have fun!', cn: '谢谢！让我们玩得开心！' },
      { speaker: 'B', text: 'Yes! Let\'s start the game!', cn: '是的！让我们开始游戏吧！' },
    ]
  },
  {
    title: '打招呼与晚上',
    icon: '🌆',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Good evening! Did you have dinner?', cn: '晚上好！你吃晚饭了吗？' },
      { speaker: 'B', text: 'Good evening! Yes, I just finished.', cn: '晚上好！是的，我刚吃完。' },
      { speaker: 'A', text: 'What did you eat?', cn: '你吃了什么？' },
      { speaker: 'B', text: 'I ate rice and fish. It was delicious!', cn: '我吃了米饭和鱼。很好吃！' },
      { speaker: 'A', text: 'Yummy! I had noodles for dinner.', cn: '好吃！我晚饭吃的是面条。' },
      { speaker: 'B', text: 'Noodles are good too! What are you doing now?', cn: '面条也很好！你现在在做什么？' },
      { speaker: 'A', text: 'I am reading a book. What about you?', cn: '我在看书。你呢？' },
      { speaker: 'B', text: 'I am watching TV with my family.', cn: '我和家人一起看电视。' },
      { speaker: 'A', text: 'That is nice. What show are you watching?', cn: '那很好。你们在看什么节目？' },
      { speaker: 'B', text: 'A cartoon show. It is very funny!', cn: '一个动画片。非常有趣！' },
    ]
  },
  {
    title: '谢谢回应',
    icon: '💕',
    color: 'bg-pink-100 dark:bg-pink-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Here is your lost pencil case.', cn: '这是你丢的铅笔盒。' },
      { speaker: 'B', text: 'Oh! Thank you so much! I was looking for it.', cn: '哦！非常感谢！我一直在找它。' },
      { speaker: 'A', text: 'I found it in the classroom.', cn: '我在教室里找到的。' },
      { speaker: 'B', text: 'You are so kind! Thank you again!', cn: '你真好！再次感谢！' },
      { speaker: 'A', text: 'You are welcome! I am happy to help.', cn: '不客气！我很乐意帮忙。' },
      { speaker: 'B', text: 'What can I do to thank you?', cn: '我能做什么来感谢你？' },
      { speaker: 'A', text: 'No need. Just be careful with your things.', cn: '不需要。只要小心保管你的东西就好。' },
      { speaker: 'B', text: 'I will! Let me treat you to ice cream!', cn: '我会的！让我请你吃冰淇淋！' },
      { speaker: 'A', text: 'That would be great! Thank you!', cn: '那太好了！谢谢！' },
      { speaker: 'B', text: 'Let\'s go get ice cream now!', cn: '让我们现在去买冰淇淋吧！' },
    ]
  },
  {
    title: '问是谁',
    icon: '❓',
    color: 'bg-slate-100 dark:bg-slate-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Who is that boy over there?', cn: '那边那个男孩是谁？' },
      { speaker: 'B', text: 'Which boy? Can you point to him?', cn: '哪个男孩？你能指给我看吗？' },
      { speaker: 'A', text: 'The one wearing a blue shirt.', cn: '那个穿蓝色衬衫的。' },
      { speaker: 'B', text: 'Oh, that is my cousin. His name is Mike.', cn: '哦，那是我的表弟。他叫迈克。' },
      { speaker: 'A', text: 'He looks very tall. How old is he?', cn: '他看起来很高。他多大了？' },
      { speaker: 'B', text: 'He is twelve years old. He plays basketball.', cn: '他十二岁。他打篮球。' },
      { speaker: 'A', text: 'That is cool! Does he go to our school?', cn: '太酷了！他在我们学校上学吗？' },
      { speaker: 'B', text: 'No, he goes to the school next door.', cn: '不，他在隔壁学校上学。' },
      { speaker: 'A', text: 'Oh, I see. Is he friendly?', cn: '哦，我明白了。他友好吗？' },
      { speaker: 'B', text: 'Yes! He is very nice. Do you want to meet him?', cn: '是的！他很好。你想认识他吗？' },
    ]
  },
  {
    title: '问这是什么',
    icon: '🔍',
    color: 'bg-amber-100 dark:bg-amber-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'What is this thing in your hand?', cn: '你手里拿的是什么东西？' },
      { speaker: 'B', text: 'This? It is a magnifying glass.', cn: '这个吗？这是一个放大镜。' },
      { speaker: 'A', text: 'What do you use it for?', cn: '你用它做什么？' },
      { speaker: 'B', text: 'I use it to see small things clearly.', cn: '我用它来清楚地看小东西。' },
      { speaker: 'A', text: 'Can I try it?', cn: '我可以试试吗？' },
      { speaker: 'B', text: 'Sure! Here, look at this leaf.', cn: '当然可以！这里，看看这片叶子。' },
      { speaker: 'A', text: 'Wow! The leaf looks so big!', cn: '哇！叶子看起来好大！' },
      { speaker: 'B', text: 'Yes! The magnifying glass makes things bigger.', cn: '是的！放大镜让东西变大。' },
      { speaker: 'A', text: 'That is amazing! Can I use it for my book?', cn: '太神奇了！我可以用它看书吗？' },
      { speaker: 'B', text: 'Of course! It helps you read small words.', cn: '当然可以！它帮你读小字。' },
    ]
  },
  {
    title: '问颜色',
    icon: '🎨',
    color: 'bg-fuchsia-100 dark:bg-fuchsia-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'What color is your backpack?', cn: '你的书包是什么颜色的？' },
      { speaker: 'B', text: 'It is pink and white. Look!', cn: '粉色和白色。看！' },
      { speaker: 'A', text: 'Pretty! What is your favorite color?', cn: '很漂亮！你最喜欢什么颜色？' },
      { speaker: 'B', text: 'My favorite color is purple. What about you?', cn: '我最喜欢的颜色是紫色。你呢？' },
      { speaker: 'A', text: 'I like blue. The sky and ocean are blue.', cn: '我喜欢蓝色。天空和海洋都是蓝色的。' },
      { speaker: 'B', text: 'Blue is beautiful too! Do you have blue clothes?', cn: '蓝色也很美！你有蓝色的衣服吗？' },
      { speaker: 'A', text: 'Yes, I have a blue T-shirt.', cn: '是的，我有一件蓝色T恤。' },
      { speaker: 'B', text: 'Nice! What color is your pencil case?', cn: '不错！你的铅笔盒是什么颜色的？' },
      { speaker: 'A', text: 'It is yellow. Yellow is bright and happy.', cn: '它是黄色的。黄色明亮又快乐。' },
      { speaker: 'B', text: 'I agree! Colors make the world beautiful!', cn: '我同意！颜色让世界美丽！' },
    ]
  },
  {
    title: '问时间',
    icon: '⏰',
    color: 'bg-teal-100 dark:bg-teal-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Excuse me, what time is it now?', cn: '打扰一下，现在几点了？' },
      { speaker: 'B', text: 'Let me check my watch. It is 9:30.', cn: '让我看看手表。9:30。' },
      { speaker: 'A', text: 'Thank you! I need to go to school soon.', cn: '谢谢！我很快要去上学了。' },
      { speaker: 'B', text: 'What time does your school start?', cn: '你的学校几点开始上课？' },
      { speaker: 'A', text: 'It starts at 10:00. I have 30 minutes.', cn: '10:00开始。我还有30分钟。' },
      { speaker: 'B', text: 'That is enough time. Do you walk to school?', cn: '时间很充足。你走路上学吗？' },
      { speaker: 'A', text: 'No, my dad drives me. He will be here soon.', cn: '不，我爸爸开车送我。他很快就到。' },
      { speaker: 'B', text: 'That is convenient. What time do you finish school?', cn: '那很方便。你几点放学？' },
      { speaker: 'A', text: 'At 4:00 pm. What about you?', cn: '下午4点。你呢？' },
      { speaker: 'B', text: 'I finish at 3:30 pm. We can play after school!', cn: '我3:30放学。我们可以放学后一起玩！' },
    ]
  },
  {
    title: '问天气',
    icon: '☀️',
    color: 'bg-sky-100 dark:bg-sky-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Is it cold outside today?', cn: '今天外面冷吗？' },
      { speaker: 'B', text: 'Yes, it is very cold. Winter is here!', cn: '是的，很冷。冬天到了！' },
      { speaker: 'A', text: 'Oh no! What should I wear?', cn: '哦不！我该穿什么？' },
      { speaker: 'B', text: 'Wear a warm coat, scarf, and gloves.', cn: '穿暖和的外套、围巾和手套。' },
      { speaker: 'A', text: 'Good idea! Did it snow last night?', cn: '好主意！昨晚下雪了吗？' },
      { speaker: 'B', text: 'Yes! Look outside, everything is white!', cn: '是的！看外面，一切都是白色的！' },
      { speaker: 'A', text: 'Wow! Can we make a snowman?', cn: '哇！我们可以堆雪人吗？' },
      { speaker: 'B', text: 'Yes! Let\'s go out and play in the snow!', cn: '可以！让我们出去在雪地里玩吧！' },
      { speaker: 'A', text: 'I will get my warm clothes. Wait for me!', cn: '我去拿我的暖和衣服。等我！' },
      { speaker: 'B', text: 'Okay! Hurry up, the snow is waiting!', cn: '好的！快点，雪花在等我们！' },
    ]
  },
  {
    title: '喜欢',
    icon: '❤️',
    color: 'bg-red-100 dark:bg-red-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you like apples?', cn: '你喜欢苹果吗？' },
      { speaker: 'B', text: 'Yes, I love apples! They are sweet and healthy.', cn: '是的，我爱苹果！它们又甜又健康。' },
      { speaker: 'A', text: 'Me too! What fruit do you like best?', cn: '我也是！你最喜欢什么水果？' },
      { speaker: 'B', text: 'I like bananas best. They are so yummy!', cn: '我最喜欢香蕉。它们太好吃了！' },
      { speaker: 'A', text: 'Bananas are good! What about strawberries?', cn: '香蕉很好！草莓呢？' },
      { speaker: 'B', text: 'I like strawberries too! They are red and sweet.', cn: '我也喜欢草莓！它们又红又甜。' },
      { speaker: 'A', text: 'I have some strawberries at home. Want some?', cn: '我家有一些草莓。想要一些吗？' },
      { speaker: 'B', text: 'Yes, please! That is very kind of you!', cn: '好的，请给我一些！你真好！' },
      { speaker: 'A', text: 'Come to my house after school!', cn: '放学后来我家吧！' },
      { speaker: 'B', text: 'Great! I will bring some bananas too!', cn: '太好了！我也会带一些香蕉！' },
    ]
  },
  {
    title: '不喜欢',
    icon: '💔',
    color: 'bg-gray-100 dark:bg-gray-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you like milk?', cn: '你喜欢牛奶吗？' },
      { speaker: 'B', text: 'No, I do not like milk very much.', cn: '不，我不太喜欢牛奶。' },
      { speaker: 'A', text: 'Really? Why don\'t you like it?', cn: '真的吗？你为什么不喜欢？' },
      { speaker: 'B', text: 'I don\'t like the taste. What about you?', cn: '我不喜欢那个味道。你呢？' },
      { speaker: 'A', text: 'I like milk. It helps me grow tall.', cn: '我喜欢牛奶。它帮我长高。' },
      { speaker: 'B', text: 'That is good. What drink do you like?', cn: '那很好。你喜欢什么饮料？' },
      { speaker: 'A', text: 'I like orange juice. It is fresh.', cn: '我喜欢橙汁。很新鲜。' },
      { speaker: 'B', text: 'Me too! Orange juice is my favorite!', cn: '我也是！橙汁是我的最爱！' },
      { speaker: 'A', text: 'Let\'s drink orange juice together then!', cn: '那我们一起喝橙汁吧！' },
      { speaker: 'B', text: 'Yes! That sounds delicious!', cn: '好的！听起来很美味！' },
    ]
  },
  {
    title: '想吃',
    icon: '🍎',
    color: 'bg-green-100 dark:bg-green-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you want a cookie? I baked them today.', cn: '你想要一个饼干吗？我今天烤的。' },
      { speaker: 'B', text: 'Yes, please! I love cookies!', cn: '好的，请给我！我喜欢饼干！' },
      { speaker: 'A', text: 'Here you go! Tell me if you like it.', cn: '给你！告诉我你喜欢吗。' },
      { speaker: 'B', text: 'Yum! This is delicious! Did you make this?', cn: '好吃！这太美味了！是你做的吗？' },
      { speaker: 'A', text: 'Yes! I learned from my mom.', cn: '是的！我跟我妈妈学的。' },
      { speaker: 'B', text: 'You are a great baker! Can I have another?', cn: '你是个很棒的烘焙师！我可以再要一个吗？' },
      { speaker: 'A', text: 'Of course! Here, take as many as you want.', cn: '当然可以！这里，想要多少拿多少。' },
      { speaker: 'B', text: 'Thank you! These are the best cookies!', cn: '谢谢！这是最好吃的饼干！' },
      { speaker: 'A', text: 'I am glad you like them! I can bake more.', cn: '我很高兴你喜欢！我可以多烤一些。' },
      { speaker: 'B', text: 'Yes, please! I want to learn too!', cn: '是的，拜托了！我也想学！' },
    ]
  },
  {
    title: '不想吃',
    icon: '🍪',
    color: 'bg-amber-100 dark:bg-amber-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you want some cake? It is chocolate!', cn: '你想要一些蛋糕吗？是巧克力的！' },
      { speaker: 'B', text: 'No, thank you. I am not hungry.', cn: '不，谢谢。我不饿。' },
      { speaker: 'A', text: 'Are you sure? It is very tasty!', cn: '你确定吗？很好吃哦！' },
      { speaker: 'B', text: 'Yes, I am sure. I just ate lunch.', cn: '是的，我确定。我刚吃完午饭。' },
      { speaker: 'A', text: 'Okay. What did you have for lunch?', cn: '好的。你午饭吃了什么？' },
      { speaker: 'B', text: 'I had rice and beef. I am full now.', cn: '我吃了米饭和牛肉。我现在很饱。' },
      { speaker: 'A', text: 'That sounds good. Do you want some water?', cn: '听起来不错。你想喝水吗？' },
      { speaker: 'B', text: 'Yes, please! Some water would be nice.', cn: '好的，请给我一些！喝水真好。' },
      { speaker: 'A', text: 'Here is some water. Do you need anything else?', cn: '这里有一些水。还需要别的吗？' },
      { speaker: 'B', text: 'No, thank you. I am good now.', cn: '不需要了，谢谢。我现在很好。' },
    ]
  },
  {
    title: '高兴',
    icon: '😊',
    color: 'bg-yellow-100 dark:bg-yellow-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'You look so happy today!', cn: '你今天看起来好开心！' },
      { speaker: 'B', text: 'Yes, I am very happy today!', cn: '是的，我今天很开心！' },
      { speaker: 'A', text: 'Why are you so happy?', cn: '你为什么这么开心？' },
      { speaker: 'B', text: 'I got an A on my math test!', cn: '我数学考试得了A！' },
      { speaker: 'A', text: 'Wow! That is amazing! Congratulations!', cn: '哇！太棒了！恭喜你！' },
      { speaker: 'B', text: 'Thank you! I studied very hard for it.', cn: '谢谢！我为此非常努力地学习。' },
      { speaker: 'A', text: 'Your hard work paid off! Are your parents happy?', cn: '你的努力得到了回报！你父母开心吗？' },
      { speaker: 'B', text: 'Yes, they are very proud of me!', cn: '是的，他们为我感到骄傲！' },
      { speaker: 'A', text: 'You should be proud of yourself too!', cn: '你也应该为自己感到骄傲！' },
      { speaker: 'B', text: 'I am! Today is the best day!', cn: '我也是！今天是最好的一天！' },
    ]
  },
  {
    title: '难过',
    icon: '😢',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'You look sad today. What is wrong?', cn: '你今天看起来很伤心。怎么了？' },
      { speaker: 'B', text: 'I am sad because I lost my favorite toy.', cn: '我很难过，因为我丢了我最喜欢的玩具。' },
      { speaker: 'A', text: 'Oh no! That is terrible. What happened?', cn: '哦不！那太糟糕了。发生了什么？' },
      { speaker: 'B', text: 'I left it at the park. Now I can\'t find it.', cn: '我把它忘在公园了。现在找不到了。' },
      { speaker: 'A', text: 'Don\'t cry. Let\'s look for it together.', cn: '别哭。让我们一起找找吧。' },
      { speaker: 'B', text: 'Really? Will you help me?', cn: '真的吗？你会帮我吗？' },
      { speaker: 'A', text: 'Of course! Tell me where you played.', cn: '当然！告诉我你在哪里玩的。' },
      { speaker: 'B', text: 'Near the slide. I hope we can find it.', cn: '在滑梯附近。我希望我们能找到它。' },
      { speaker: 'A', text: 'I am sure we will find it. Let\'s go now!', cn: '我确定我们会找到的。我们现在就出发！' },
      { speaker: 'B', text: 'Thank you! You are such a good friend!', cn: '谢谢！你真是个好朋友！' },
    ]
  },
  {
    title: '累',
    icon: '😴',
    color: 'bg-purple-100 dark:bg-purple-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'You look tired today. Did you sleep well?', cn: '你今天看起来很累。睡得好吗？' },
      { speaker: 'B', text: 'No, I am very tired today.', cn: '不，我今天很累。' },
      { speaker: 'A', text: 'Why are you so tired? What did you do?', cn: '你为什么这么累？你做了什么？' },
      { speaker: 'B', text: 'I had sports day at school. I ran a lot.', cn: '学校有运动会。我跑了很多。' },
      { speaker: 'A', text: 'That is tiring! You should rest.', cn: '那确实累人！你应该休息。' },
      { speaker: 'B', text: 'Yes, I want to go home and sleep.', cn: '是的，我想回家睡觉。' },
      { speaker: 'A', text: 'Do you want me to walk you home?', cn: '你想让我送你回家吗？' },
      { speaker: 'B', text: 'Thank you, that would be nice.', cn: '谢谢，那很好。' },
      { speaker: 'A', text: 'Let\'s go. Take a good rest when you get home.', cn: '我们走吧。回家后好好休息。' },
      { speaker: 'B', text: 'I will. Thank you for your care!', cn: '我会的。谢谢你的关心！' },
    ]
  },
  {
    title: '饿',
    icon: '🍽️',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'My stomach is making noises. I am hungry!', cn: '我的肚子在咕咕叫。我饿了！' },
      { speaker: 'B', text: 'I am hungry too! Let\'s get some food.', cn: '我也饿了！我们去弄点吃的吧。' },
      { speaker: 'A', text: 'What do you want to eat?', cn: '你想吃什么？' },
      { speaker: 'B', text: 'I want pizza. What about you?', cn: '我想要披萨。你呢？' },
      { speaker: 'A', text: 'Pizza sounds great! Where can we get pizza?', cn: '披萨听起来很棒！我们在哪里可以买到披萨？' },
      { speaker: 'B', text: 'There is a pizza shop near here.', cn: '这附近有一家披萨店。' },
      { speaker: 'A', text: 'Perfect! Let\'s go there now!', cn: '完美！我们现在就去吧！' },
      { speaker: 'B', text: 'How much money do you have?', cn: '你有多少钱？' },
      { speaker: 'A', text: 'I have 20 yuan. Is that enough?', cn: '我有20元。够吗？' },
      { speaker: 'B', text: 'Yes! We can share a pizza together!', cn: '够了！我们可以一起分享一个披萨！' },
    ]
  },
  {
    title: '渴',
    icon: '💧',
    color: 'bg-cyan-100 dark:bg-cyan-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'It is so hot today. I am very thirsty.', cn: '今天太热了。我很渴。' },
      { speaker: 'B', text: 'Me too! Let\'s find something to drink.', cn: '我也是！让我们找点喝的吧。' },
      { speaker: 'A', text: 'What do you want to drink?', cn: '你想喝什么？' },
      { speaker: 'B', text: 'I want ice water. It cools you down.', cn: '我想要冰水。它让你降温。' },
      { speaker: 'A', text: 'Good idea! I want cold juice.', cn: '好主意！我想要冷果汁。' },
      { speaker: 'B', text: 'Let\'s go to the store. What juice do you want?', cn: '让我们去商店吧。你想要什么果汁？' },
      { speaker: 'A', text: 'Apple juice, please. What about you?', cn: '请给我苹果汁。你呢？' },
      { speaker: 'B', text: 'I will get water. Let\'s go!', cn: '我去拿水。我们走吧！' },
      { speaker: 'A', text: 'Wait, let me get my money.', cn: '等等，让我拿钱。' },
      { speaker: 'B', text: 'Okay! Hurry up, I am so thirsty!', cn: '好的！快点，我太渴了！' },
    ]
  },
  {
    title: '帮忙',
    icon: '🤝',
    color: 'bg-emerald-100 dark:bg-emerald-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Can you help me with my homework?', cn: '你能帮我做作业吗？' },
      { speaker: 'B', text: 'Of course! What homework is it?', cn: '当然可以！是什么作业？' },
      { speaker: 'A', text: 'It is math. I don\'t understand this problem.', cn: '是数学。我不明白这道题。' },
      { speaker: 'B', text: 'Let me see. Oh, this is subtraction.', cn: '让我看看。哦，这是减法。' },
      { speaker: 'A', text: 'Can you explain how to do it?', cn: '你能解释怎么做吗？' },
      { speaker: 'B', text: 'Sure! You take the small number from the big number.', cn: '当然！你用大数减去小数。' },
      { speaker: 'A', text: 'Like this? 10 minus 5 equals 5?', cn: '像这样？10减5等于5？' },
      { speaker: 'B', text: 'Yes! You got it! You are smart!', cn: '是的！你懂了！你很聪明！' },
      { speaker: 'A', text: 'Thank you! You are a great teacher!', cn: '谢谢！你是个很棒的老师！' },
      { speaker: 'B', text: 'Anytime! Ask me if you need help again.', cn: '随时！如果你再需要帮忙就问我。' },
    ]
  },
  {
    title: '需要',
    icon: '✨',
    color: 'bg-violet-100 dark:bg-violet-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'I need a new pencil. Mine is broken.', cn: '我需要一支新铅笔。我的坏了。' },
      { speaker: 'B', text: 'Oh no! Do you have another one?', cn: '哦不！你有另一支吗？' },
      { speaker: 'A', text: 'No, I don\'t. Can you help me?', cn: '没有。你能帮我吗？' },
      { speaker: 'B', text: 'Sure! I can give you one of mine.', cn: '当然可以！我可以给你我的一支。' },
      { speaker: 'A', text: 'Really? Thank you so much!', cn: '真的吗？非常感谢！' },
      { speaker: 'B', text: 'You are welcome! What color do you want?', cn: '不客气！你想要什么颜色？' },
      { speaker: 'A', text: 'Blue is my favorite. Do you have blue?', cn: '蓝色是我最喜欢的。你有蓝色的吗？' },
      { speaker: 'B', text: 'Yes! Here is a blue pencil for you.', cn: '有！这里有一支蓝色铅笔给你。' },
      { speaker: 'A', text: 'Thank you! You are so kind!', cn: '谢谢！你真好！' },
      { speaker: 'B', text: 'No problem! Let me know if you need anything else.', cn: '没问题！如果你还需要别的就告诉我。' },
    ]
  },
  {
    title: '有',
    icon: '✅',
    color: 'bg-green-100 dark:bg-green-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you have a ruler I can borrow?', cn: '我有直尺可以借吗？' },
      { speaker: 'B', text: 'Yes, I have one. Here you go.', cn: '是的，我有一把。给你。' },
      { speaker: 'A', text: 'Thank you! I will return it soon.', cn: '谢谢！我很快就还给你。' },
      { speaker: 'B', text: 'Take your time. Do you need anything else?', cn: '慢慢来。还需要别的吗？' },
      { speaker: 'A', text: 'Do you have an eraser too?', cn: '你也有橡皮吗？' },
      { speaker: 'B', text: 'Yes, I have a white eraser.', cn: '有的，我有一块白色橡皮。' },
      { speaker: 'A', text: 'Great! Can I borrow that too?', cn: '太好了！我也可以借那个吗？' },
      { speaker: 'B', text: 'Sure! Here is the eraser.', cn: '当然可以！这是橡皮。' },
      { speaker: 'A', text: 'Thank you! You always have everything!', cn: '谢谢！你总是什么都有！' },
      { speaker: 'B', text: 'I come prepared! Let me know if you need more.', cn: '我准备很充分！如果你需要更多就告诉我。' },
    ]
  },
  {
    title: '没有',
    icon: '❌',
    color: 'bg-red-100 dark:bg-red-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you have a color pencil? I need one.', cn: '你有彩笔吗？我需要一支。' },
      { speaker: 'B', text: 'Sorry, I don\'t have any color pencils.', cn: '对不起，我没有彩笔。' },
      { speaker: 'A', text: 'Oh, that is okay. Do you know who has one?', cn: '哦，没关系。你知道谁有吗？' },
      { speaker: 'B', text: 'Maybe Lily has some. She loves drawing.', cn: '也许莉莉有一些。她喜欢画画。' },
      { speaker: 'A', text: 'Good idea! Where is Lily?', cn: '好主意！莉莉在哪里？' },
      { speaker: 'B', text: 'She is over there, by the window.', cn: '她在那边，窗户旁边。' },
      { speaker: 'A', text: 'Thank you! I will ask her.', cn: '谢谢！我去问问她。' },
      { speaker: 'B', text: 'Good luck! I hope she can help you.', cn: '祝好运！希望她能帮你。' },
      { speaker: 'A', text: 'Thanks! If she doesn\'t have, I will ask the teacher.', cn: '谢谢！如果她没有，我会问老师。' },
      { speaker: 'B', text: 'That is a good backup plan. See you later!', cn: '那是个好备选方案。待会儿见！' },
    ]
  },
  {
    title: '在哪里',
    icon: '📍',
    color: 'bg-rose-100 dark:bg-rose-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Where is my school bag? I can\'t find it!', cn: '我的书包在哪里？我找不到！' },
      { speaker: 'B', text: 'Did you check under your desk?', cn: '你检查桌子底下了吗？' },
      { speaker: 'A', text: 'Yes, it is not there. I am worried!', cn: '是的，不在那里。我担心！' },
      { speaker: 'B', text: 'Don\'t worry. Let\'s look for it together.', cn: '别担心。让我们一起找找。' },
      { speaker: 'A', text: 'Where should we look first?', cn: '我们应该先找哪里？' },
      { speaker: 'B', text: 'Let\'s check the classroom lost and found.', cn: '让我们检查教室的失物招领处。' },
      { speaker: 'A', text: 'Good idea! What does your bag look like?', cn: '好主意！你的书包是什么样子的？' },
      { speaker: 'B', text: 'It is blue with a cat on it.', cn: '蓝色的，上面有一只猫。' },
      { speaker: 'A', text: 'Oh, I see a blue bag over there!', cn: '哦，我在那边看到一个蓝色书包！' },
      { speaker: 'B', text: 'Yes! That is mine! Thank you for helping me!', cn: '是的！那是我的！谢谢你的帮助！' },
    ]
  },
  {
    title: '在做什么',
    icon: '🏃',
    color: 'bg-indigo-100 dark:bg-indigo-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Hi! What are you doing now?', cn: '嗨！你在做什么？' },
      { speaker: 'B', text: 'I am reading an interesting book.', cn: '我在读一本有趣的书。' },
      { speaker: 'A', text: 'What is the book about?', cn: '这本书是关于什么的？' },
      { speaker: 'B', text: 'It is about animals in the forest.', cn: '是关于森林里的动物的。' },
      { speaker: 'A', text: 'That sounds fun! What animals are in the book?', cn: '听起来很有趣！书里有什么动物？' },
      { speaker: 'B', text: 'Bears, rabbits, and many birds!', cn: '熊、兔子，还有很多鸟！' },
      { speaker: 'A', text: 'I like animals! Can I read it with you?', cn: '我喜欢动物！我可以和你一起读吗？' },
      { speaker: 'B', text: 'Sure! Come sit next to me.', cn: '当然可以！来坐在我旁边。' },
      { speaker: 'A', text: 'Thank you! Let\'s read together!', cn: '谢谢！让我们一起读吧！' },
      { speaker: 'B', text: 'Okay! I will start from page one.', cn: '好的！我从第一页开始。' },
    ]
  },
  {
    title: '去哪里',
    icon: '🚶',
    color: 'bg-lime-100 dark:bg-lime-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Where are you going with your bag?', cn: '你背着包要去哪里？' },
      { speaker: 'B', text: 'I am going to the library.', cn: '我要去图书馆。' },
      { speaker: 'A', text: 'What are you going to do there?', cn: '你要去那里做什么？' },
      { speaker: 'B', text: 'I am going to borrow some books.', cn: '我要借一些书。' },
      { speaker: 'A', text: 'What kind of books do you want?', cn: '你想要什么样的书？' },
      { speaker: 'B', text: 'Storybooks and science books.', cn: '故事书和科学书。' },
      { speaker: 'A', text: 'Can I go with you? I need books too.', cn: '我可以和你一起去吗？我也需要书。' },
      { speaker: 'B', text: 'Of course! Let\'s go together!', cn: '当然可以！我们一起去吧！' },
      { speaker: 'A', text: 'What books do you need?', cn: '你需要什么书？' },
      { speaker: 'B', text: 'I need a book about dinosaurs!', cn: '我需要一本关于恐龙的书！' },
    ]
  },
  {
    title: '请求允许',
    icon: '🙋',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Teacher, may I go to the restroom?', cn: '老师，我可以去洗手间吗？' },
      { speaker: 'B', text: 'Yes, you may. But be quick, okay?', cn: '可以的。但要快点，好吗？' },
      { speaker: 'A', text: 'Thank you! I will come back soon.', cn: '谢谢！我很快就回来。' },
      { speaker: 'B', text: 'Okay. Don\'t run in the hallway.', cn: '好的。不要在走廊里跑。' },
      { speaker: 'A', text: 'I won\'t. May my friend go too?', cn: '我不会的。我朋友也可以去吗？' },
      { speaker: 'B', text: 'Yes, but you two need to come back together.', cn: '可以，但你们两个需要一起回来。' },
      { speaker: 'A', text: 'We will! Thank you, teacher!', cn: '我们会回来的！谢谢老师！' },
      { speaker: 'B', text: 'You are welcome. Go ahead.', cn: '不客气。去吧。' },
      { speaker: 'A', text: 'See you in a few minutes!', cn: '几分钟后见！' },
      { speaker: 'B', text: 'See you soon!', cn: '很快见！' },
    ]
  },
  {
    title: '同意',
    icon: '👍',
    color: 'bg-green-100 dark:bg-green-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you think this picture is beautiful?', cn: '你认为这幅画美吗？' },
      { speaker: 'B', text: 'Yes, I think it is very beautiful!', cn: '是的，我认为它非常美！' },
      { speaker: 'A', text: 'What do you like about it?', cn: '你喜欢它什么？' },
      { speaker: 'B', text: 'The colors are so bright and pretty.', cn: '颜色很鲜艳漂亮。' },
      { speaker: 'A', text: 'I agree! The flowers look real!', cn: '我同意！这些花看起来像真的一样！' },
      { speaker: 'B', text: 'Yes! And the sky is so blue!', cn: '是的！天空那么蓝！' },
      { speaker: 'A', text: 'Who painted this picture?', cn: '谁画的这幅画？' },
      { speaker: 'B', text: 'I think it was Lily. She is good at art.', cn: '我想是莉莉画的。她擅长美术。' },
      { speaker: 'A', text: 'She is talented! Let\'s tell her we like it.', cn: '她很有才华！让我们告诉她我们喜欢。' },
      { speaker: 'B', text: 'Good idea! She will be happy to hear that!', cn: '好主意！她听到会很高兴的！' },
    ]
  },
  {
    title: '不同意',
    icon: '👎',
    color: 'bg-red-100 dark:bg-red-900',
    level: 1,
    scenario: [
      { speaker: 'A', text: 'Do you think spinach is delicious?', cn: '你认为菠菜好吃吗？' },
      { speaker: 'B', text: 'No, I don\'t think so. I don\'t like it.', cn: '不，我不这么认为。我不喜欢它。' },
      { speaker: 'A', text: 'Really? I think it is good for health.', cn: '真的吗？我认为它对健康有益。' },
      { speaker: 'B', text: 'I know, but I don\'t like the taste.', cn: '我知道，但我不喜欢那个味道。' },
      { speaker: 'A', text: 'What vegetables do you like then?', cn: '那你喜欢什么蔬菜？' },
      { speaker: 'B', text: 'I like carrots and tomatoes.', cn: '我喜欢胡萝卜和西红柿。' },
      { speaker: 'A', text: 'Those are good too! Do you eat them every day?', cn: '那些也不错！你每天都吃吗？' },
      { speaker: 'B', text: 'Yes, my mom puts them in my meals.', cn: '是的，我妈妈把它们放在我的饭菜里。' },
      { speaker: 'A', text: 'That is good! Your mom cares about your health.', cn: '那很好！你妈妈关心你的健康。' },
      { speaker: 'B', text: 'Yes, I know. I should try to like spinach too.', cn: '是的，我知道。我也应该试着喜欢菠菜。' },
    ]
  },

  // === Level 2: 日常生活场景 (41-80) ===
  {
    title: '自我介绍',
    icon: '🤝',
    color: 'bg-green-100 dark:bg-green-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Hi, what is your name?', cn: '嗨，你叫什么名字？' },
      { speaker: 'B', text: 'My name is Tom. What about you?', cn: '我叫汤姆。你呢？' },
      { speaker: 'A', text: 'I am Amy. Nice to meet you!', cn: '我是艾米。很高兴认识你！' },
      { speaker: 'B', text: 'Nice to meet you too! Where are you from?', cn: '我也很高兴认识你！你来自哪里？' },
      { speaker: 'A', text: 'I am from Beijing. What about you?', cn: '我来自北京。你呢？' },
      { speaker: 'B', text: 'I am from Shanghai. Beijing is beautiful!', cn: '我来自上海。北京很美！' },
      { speaker: 'A', text: 'Thank you! Shanghai is beautiful too!', cn: '谢谢！上海也很美！' },
      { speaker: 'B', text: 'Do you have any brothers or sisters?', cn: '你有兄弟姐妹吗？' },
      { speaker: 'A', text: 'I have one younger brother. What about you?', cn: '我有一个弟弟。你呢？' },
      { speaker: 'B', text: 'I am an only child. Let\'s be friends!', cn: '我是独生子。让我们做朋友吧！' },
    ]
  },
  {
    title: '问路',
    icon: '🗺️',
    color: 'bg-purple-100 dark:bg-purple-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Excuse me, where is the library?', cn: '打扰一下，图书馆在哪里？' },
      { speaker: 'B', text: 'Go straight and turn left. You can see it.', cn: '直走然后左转，你就能看到了。' },
      { speaker: 'A', text: 'How long does it take to walk there?', cn: '步行去那里要多久？' },
      { speaker: 'B', text: 'About 10 minutes. It is not far.', cn: '大约10分钟。不远。' },
      { speaker: 'A', text: 'Thank you! Is there a big sign?', cn: '谢谢！有大标志吗？' },
      { speaker: 'B', text: 'Yes, it has a red sign. You can\'t miss it.', cn: '是的，有红色的标志。你不会错过的。' },
      { speaker: 'A', text: 'What are the library hours today?', cn: '图书馆今天开放时间是几点？' },
      { speaker: 'B', text: 'It opens at 9 am and closes at 9 pm.', cn: '上午9点开，晚上9点关。' },
      { speaker: 'A', text: 'Thank you very much for your help!', cn: '非常感谢你的帮助！' },
      { speaker: 'B', text: 'You are welcome! Enjoy your visit!', cn: '不客气！祝你参观愉快！' },
    ]
  },
  {
    title: '购物',
    icon: '🛒',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'How much is this apple?', cn: '这个苹果多少钱？' },
      { speaker: 'B', text: 'It is two yuan per kilogram.', cn: '一公斤两元。' },
      { speaker: 'A', text: 'Can I buy just one?', cn: '我可以只买一个吗？' },
      { speaker: 'B', text: 'Sure! This one is big and sweet.', cn: '当然可以！这个又大又甜。' },
      { speaker: 'A', text: 'I will take two, please.', cn: '我要两个，谢谢。' },
      { speaker: 'B', text: 'Here you are. That is four yuan.', cn: '给你。总共四元。' },
      { speaker: 'A', text: 'Do you have any bananas too?', cn: '你有香蕉吗？' },
      { speaker: 'B', text: 'Yes, fresh bananas are over there.', cn: '有，新鲜香蕉在那边。' },
      { speaker: 'A', text: 'How much are they?', cn: '香蕉多少钱？' },
      { speaker: 'B', text: 'Five yuan per kilogram. Would you like some?', cn: '一公斤五元。想要一些吗？' },
    ]
  },
  {
    title: '点餐',
    icon: '🍽️',
    color: 'bg-red-100 dark:bg-red-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Good morning! Can I help you?', cn: '早上好！我能帮你吗？' },
      { speaker: 'B', text: 'Yes, please. I would like a hamburger.', cn: '是的，请给我一个汉堡。' },
      { speaker: 'A', text: 'What would you like to drink?', cn: '你想喝点什么？' },
      { speaker: 'B', text: 'A glass of orange juice, please.', cn: '一杯橙汁，谢谢。' },
      { speaker: 'A', text: 'Anything else? How about some fries?', cn: '还要别的吗？要一些薯条吗？' },
      { speaker: 'B', text: 'No, that is all. Thank you.', cn: '不要了，就这些。谢谢。' },
      { speaker: 'A', text: 'Is this for here or to go?', cn: '这里吃还是带走？' },
      { speaker: 'B', text: 'For here, please.', cn: '这里吃，谢谢。' },
      { speaker: 'A', text: 'That will be 25 yuan. Please pay here.', cn: '总共25元。请在这里付款。' },
      { speaker: 'B', text: 'Here is the money. Thank you!', cn: '这是钱。谢谢！' },
    ]
  },
  {
    title: '在课堂上',
    icon: '📚',
    color: 'bg-cyan-100 dark:bg-cyan-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Good morning, teacher!', cn: '早上好，老师！' },
      { speaker: 'B', text: 'Good morning, class! Let\'s begin our lesson.', cn: '早上好，同学们！让我们开始上课。' },
      { speaker: 'A', text: 'Teacher, can I go to the bathroom?', cn: '老师，我可以去洗手间吗？' },
      { speaker: 'B', text: 'Yes, you can. But be quick, okay?', cn: '可以，但要快点，好吗？' },
      { speaker: 'A', text: 'Thank you! I will be back soon.', cn: '谢谢！我很快就回来。' },
      { speaker: 'B', text: 'Okay. Don\'t forget to wash your hands.', cn: '好的。别忘了洗手。' },
      { speaker: 'A', text: 'I won\'t. May I take a break too?', cn: '我不会的。我可以休息一下吗？' },
      { speaker: 'B', text: 'After we finish this page, we will have a break.', cn: '我们学完这一页后，我们休息一下。' },
      { speaker: 'A', text: 'Okay, I will wait. Thank you, teacher.', cn: '好的，我会等。谢谢老师。' },
      { speaker: 'B', text: 'You are welcome. Now open your books.', cn: '不客气。现在打开书。' },
    ]
  },
  {
    title: '打电话',
    icon: '📞',
    color: 'bg-pink-100 dark:bg-pink-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Hello, this is Tom. May I speak to Amy?', cn: '你好，我是汤姆。我可以找艾米吗？' },
      { speaker: 'B', text: 'This is Amy. How are you?', cn: '我是艾米。你好吗？' },
      { speaker: 'A', text: 'I am fine. Do you want to play together?', cn: '我很好。你想一起玩吗？' },
      { speaker: 'B', text: 'Sure! What time?', cn: '当然！什么时间？' },
      { speaker: 'A', text: 'How about 3 o\'clock this afternoon?', cn: '今天下午3点怎么样？' },
      { speaker: 'B', text: 'Perfect! Where should we meet?', cn: '太好了！我们在哪里见面？' },
      { speaker: 'A', text: 'Let\'s meet at the park entrance.', cn: '让我们在公园门口见。' },
      { speaker: 'B', text: 'Great! What should we bring?', cn: '太好了！我们应该带什么？' },
      { speaker: 'A', text: 'I will bring a ball. You bring some water.', cn: '我会带一个球。你带一些水。' },
      { speaker: 'B', text: 'Okay! See you then! Bye!', cn: '好的！到时候见！再见！' },
    ]
  },
  {
    title: '谈论天气',
    icon: '🌤️',
    color: 'bg-yellow-100 dark:bg-yellow-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What is the weather like today?', cn: '今天天气怎么样？' },
      { speaker: 'B', text: 'It is sunny and warm. Perfect for a picnic!', cn: '今天很晴朗温暖。适合野餐！' },
      { speaker: 'A', text: 'That is great! Let us go to the park.', cn: '太棒了！我们去公园吧。' },
      { speaker: 'B', text: 'Good idea! What food should we bring?', cn: '好主意！我们应该带什么食物？' },
      { speaker: 'A', text: 'Let\'s bring sandwiches and fruits.', cn: '让我们带三明治和水果。' },
      { speaker: 'B', text: 'I can bring drinks and snacks.', cn: '我可以带饮料和零食。' },
      { speaker: 'A', text: 'Perfect! What time should we go?', cn: '完美！我们什么时候去？' },
      { speaker: 'B', text: 'How about 10 o\'clock in the morning?', cn: '上午10点怎么样？' },
      { speaker: 'A', text: 'Okay! Should we invite our friends?', cn: '好的！我们应该邀请我们的朋友吗？' },
      { speaker: 'B', text: 'Yes! The more, the merrier!', cn: '是的！人越多越开心！' },
    ]
  },
  {
    title: '买文具',
    icon: '✏️',
    color: 'bg-indigo-100 dark:bg-indigo-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'I need a pencil and a notebook.', cn: '我需要一支铅笔和一个笔记本。' },
      { speaker: 'B', text: 'Here you are. Anything else?', cn: '给你。还要别的吗？' },
      { speaker: 'A', text: 'Do you have erasers too?', cn: '你有橡皮吗？' },
      { speaker: 'B', text: 'Yes, we have white and pink erasers.', cn: '有的，我们有白色和粉色橡皮。' },
      { speaker: 'A', text: 'I will take a white one, please.', cn: '请给我一个白色的。' },
      { speaker: 'B', text: 'Sure. Do you need a ruler too?', cn: '当然可以。你需要尺子吗？' },
      { speaker: 'A', text: 'Yes, I do. How much for everything?', cn: '是的，我需要。所有东西多少钱？' },
      { speaker: 'B', text: 'That will be 15 yuan in total.', cn: '总共15元。' },
      { speaker: 'A', text: 'Here is the money. Thank you!', cn: '这是钱。谢谢！' },
      { speaker: 'B', text: 'You are welcome! Come again!', cn: '不客气！欢迎再来！' },
    ]
  },
  {
    title: '借东西',
    icon: '📚',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Can I borrow your pen?', cn: '我可以借你的笔吗？' },
      { speaker: 'B', text: 'Sure, here you are. What do you need it for?', cn: '当然，给你。你需要它做什么？' },
      { speaker: 'A', text: 'I need to write down my homework.', cn: '我需要记下我的作业。' },
      { speaker: 'B', text: 'Okay. When will you return it?', cn: '好的。你什么时候还？' },
      { speaker: 'A', text: 'I will return it after class.', cn: '我下课后还给你。' },
      { speaker: 'B', text: 'No problem. Take your time.', cn: '没问题。慢慢来。' },
      { speaker: 'A', text: 'Thank you! You are always helpful.', cn: '谢谢！你总是很乐于助人。' },
      { speaker: 'B', text: 'I am happy to help. Do you need anything else?', cn: '我很乐意帮忙。还需要别的吗？' },
      { speaker: 'A', text: 'No, that is all. Thanks again!', cn: '不需要了，就这些。再次感谢！' },
      { speaker: 'B', text: 'You are welcome!', cn: '不客气！' },
    ]
  },
  {
    title: '约朋友',
    icon: '📅',
    color: 'bg-emerald-100 dark:bg-emerald-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Do you want to play football tomorrow?', cn: '你明天想踢足球吗？' },
      { speaker: 'B', text: 'Yes! What time should we meet?', cn: '想！我们几点见面？' },
      { speaker: 'A', text: 'How about 4 o\'clock at the park?', cn: '下午4点在公园怎么样？' },
      { speaker: 'B', text: 'Perfect! Should I bring a ball?', cn: '太好了！我应该带球吗？' },
      { speaker: 'A', text: 'Yes, please. I will bring water.', cn: '是的，请带球。我会带水。' },
      { speaker: 'B', text: 'Great! Who else should we invite?', cn: '太好了！我们还应该邀请谁？' },
      { speaker: 'A', text: 'Let\'s invite Jack and Mike.', cn: '让我们邀请杰克和迈克。' },
      { speaker: 'B', text: 'Good idea! They love football too.', cn: '好主意！他们也喜欢足球。' },
      { speaker: 'A', text: 'I will call them now.', cn: '我现在就给他们打电话。' },
      { speaker: 'B', text: 'Okay! See you tomorrow!', cn: '好的！明天见！' },
    ]
  },
  {
    title: '谈论爱好',
    icon: '🎨',
    color: 'bg-purple-100 dark:bg-purple-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What is your hobby?', cn: '你的爱好是什么？' },
      { speaker: 'B', text: 'I like drawing pictures.', cn: '我喜欢画画。' },
      { speaker: 'A', text: 'That is cool! What do you like to draw?', cn: '太酷了！你喜欢画什么？' },
      { speaker: 'B', text: 'I like drawing animals and nature.', cn: '我喜欢画动物和自然。' },
      { speaker: 'A', text: 'I like reading books. What about you?', cn: '我喜欢看书。你呢？' },
      { speaker: 'B', text: 'Reading is fun too! What do you read?', cn: '看书也很有趣！你看什么书？' },
      { speaker: 'A', text: 'I read storybooks about adventures.', cn: '我看冒险故事书。' },
      { speaker: 'B', text: 'Sounds interesting! Can I borrow one?', cn: '听起来很有趣！我可以借一本吗？' },
      { speaker: 'A', text: 'Of course! I will bring one tomorrow.', cn: '当然可以！我明天带一本给你。' },
      { speaker: 'B', text: 'Thank you! I am excited to read it!', cn: '谢谢！我很期待读它！' },
    ]
  },
  {
    title: '询问星期',
    icon: '📆',
    color: 'bg-teal-100 dark:bg-teal-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What day is today?', cn: '今天是星期几？' },
      { speaker: 'B', text: 'It is Monday.', cn: '今天是星期一。' },
      { speaker: 'A', text: 'Do we have school tomorrow?', cn: '我们明天上学吗？' },
      { speaker: 'B', text: 'Yes, we do. We have school on Tuesday too.', cn: '是的，我们要上学。星期二也上学。' },
      { speaker: 'A', text: 'What about the weekend?', cn: '那周末呢？' },
      { speaker: 'B', text: 'We don\'t have school on Saturday and Sunday.', cn: '我们星期六和星期日不上学。' },
      { speaker: 'A', text: 'That is good! What do you do on weekends?', cn: '那很好！你周末做什么？' },
      { speaker: 'B', text: 'I play with my friends and do my homework.', cn: '我和朋友一起玩，做作业。' },
      { speaker: 'A', text: 'Sounds fun! Can we play together this weekend?', cn: '听起来很有趣！这个周末我们可以一起玩吗？' },
      { speaker: 'B', text: 'Yes! Let\'s meet on Saturday morning!', cn: '可以！让我们星期六早上见面！' },
    ]
  },
  {
    title: '谈论周末',
    icon: '🎉',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What did you do last weekend?', cn: '你上周末做了什么？' },
      { speaker: 'B', text: 'I went to the zoo with my parents.', cn: '我和父母去动物园了。' },
      { speaker: 'A', text: 'That sounds fun! What animals did you see?', cn: '听起来很有趣！你看到了什么动物？' },
      { speaker: 'B', text: 'We saw tigers, lions, and monkeys.', cn: '我们看到了老虎、狮子和猴子。' },
      { speaker: 'A', text: 'What was your favorite animal?', cn: '你最喜欢的动物是什么？' },
      { speaker: 'B', text: 'I liked the pandas best. They are so cute!', cn: '我最喜欢熊猫。它们太可爱了！' },
      { speaker: 'A', text: 'I love pandas too! Did you take photos?', cn: '我也爱熊猫！你拍照了吗？' },
      { speaker: 'B', text: 'Yes! I took many photos. Want to see?', cn: '是的！我拍了很多照片。想看吗？' },
      { speaker: 'A', text: 'Yes! Show me your photos!', cn: '想！给我看你的照片！' },
      { speaker: 'B', text: 'Okay! Look at this one. It is eating bamboo!', cn: '好的！看这张。它正在吃竹子！' },
    ]
  },
  {
    title: '谈论食物',
    icon: '🍕',
    color: 'bg-red-100 dark:bg-red-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What is your favorite food?', cn: '你最喜欢什么食物？' },
      { speaker: 'B', text: 'My favorite food is pizza.', cn: '我最喜欢的食物是披萨。' },
      { speaker: 'A', text: 'I like pizza too! What kind of pizza?', cn: '我也喜欢披萨！什么种类的披萨？' },
      { speaker: 'B', text: 'I like cheese pizza. What about you?', cn: '我喜欢芝士披萨。你呢？' },
      { speaker: 'A', text: 'I like pepperoni pizza. What about fruit?', cn: '我喜欢意大利辣香肠披萨。那水果呢？' },
      { speaker: 'B', text: 'I like strawberries and bananas.', cn: '我喜欢草莓和香蕉。' },
      { speaker: 'A', text: 'Strawberries are my favorite too!', cn: '草莓也是我的最爱！' },
      { speaker: 'B', text: 'Do you like vegetables?', cn: '你喜欢蔬菜吗？' },
      { speaker: 'A', text: 'I like carrots and tomatoes. What about you?', cn: '我喜欢胡萝卜和西红柿。你呢？' },
      { speaker: 'B', text: 'I like broccoli. It is very healthy!', cn: '我喜欢西兰花。它非常健康！' },
    ]
  },
  {
    title: '谈论颜色',
    icon: '🌈',
    color: 'bg-fuchsia-100 dark:bg-fuchsia-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What color do you like best?', cn: '你最喜欢什么颜色？' },
      { speaker: 'B', text: 'I like blue best. It is the color of the sky.', cn: '我最喜欢蓝色。它是天空的颜色。' },
      { speaker: 'A', text: 'I like red. It is the color of apples.', cn: '我喜欢红色。它是苹果的颜色。' },
      { speaker: 'B', text: 'Red is bright and beautiful!', cn: '红色明亮又美丽！' },
      { speaker: 'A', text: 'What color is your room?', cn: '你的房间是什么颜色的？' },
      { speaker: 'B', text: 'My room is yellow. It makes me happy.', cn: '我的房间是黄色的。它让我快乐。' },
      { speaker: 'A', text: 'My room is green. It feels like nature.', cn: '我的房间是绿色的。感觉像大自然。' },
      { speaker: 'B', text: 'Green is peaceful. What is your favorite clothes color?', cn: '绿色很平静。你最喜欢的衣服颜色是什么？' },
      { speaker: 'A', text: 'I like wearing white. It is clean.', cn: '我喜欢穿白色。它很干净。' },
      { speaker: 'B', text: 'Both colors are beautiful!', cn: '两种颜色都很美！' },
    ]
  },
  {
    title: '问路2',
    icon: '🗺️',
    color: 'bg-lime-100 dark:bg-lime-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Excuse me, how can I get to the post office?', cn: '打扰一下，我该怎么去邮局？' },
      { speaker: 'B', text: 'Go along this street, turn right at the second crossing.', cn: '沿着这条街走，在第二个路口右转。' },
      { speaker: 'A', text: 'Is it far from here?', cn: '离这里远吗？' },
      { speaker: 'B', text: 'No, it is only about 5 minutes\' walk.', cn: '不远，步行大约5分钟。' },
      { speaker: 'A', text: 'Are there any landmarks?', cn: '有什么地标吗？' },
      { speaker: 'B', text: 'Yes, it is next to a big supermarket.', cn: '有的，它在大超市旁边。' },
      { speaker: 'A', text: 'What time does the post office close?', cn: '邮局几点关门？' },
      { speaker: 'B', text: 'It closes at 5 pm today. You have time.', cn: '今天下午5点关门。你有时间。' },
      { speaker: 'A', text: 'Thank you for your help!', cn: '谢谢你的帮助！' },
      { speaker: 'B', text: 'You are welcome. Have a nice day!', cn: '不客气。祝你今天愉快！' },
    ]
  },
  {
    title: '乘坐公交',
    icon: '🚌',
    color: 'bg-yellow-100 dark:bg-yellow-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Which bus should I take to the museum?', cn: '去博物馆应该坐几路公交？' },
      { speaker: 'B', text: 'You can take bus number 5.', cn: '你可以坐5路公交。' },
      { speaker: 'A', text: 'Where is the bus stop?', cn: '公交站在哪里？' },
      { speaker: 'B', text: 'It is over there, across the street.', cn: '就在那边，街对面。' },
      { speaker: 'A', text: 'How many stops to the museum?', cn: '到博物馆要坐几站？' },
      { speaker: 'B', text: 'About 8 stops. It takes 20 minutes.', cn: '大约8站。需要20分钟。' },
      { speaker: 'A', text: 'How much is the fare?', cn: '票价多少钱？' },
      { speaker: 'B', text: 'It is 2 yuan. You can pay with a card or cash.', cn: '2元。你可以刷卡或付现金。' },
      { speaker: 'A', text: 'Thank you! What stop should I get off?', cn: '谢谢！我应该在哪站下车？' },
      { speaker: 'B', text: 'Get off at Museum Road stop. The museum is right there.', cn: '在博物馆路站下车。博物馆就在那里。' },
    ]
  },
  {
    title: '看电影',
    icon: '🎬',
    color: 'bg-rose-100 dark:bg-rose-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Do you want to watch a movie with me?', cn: '你想和我一起看电影吗？' },
      { speaker: 'B', text: 'Sure! What movie do you want to watch?', cn: '当然！你想看什么电影？' },
      { speaker: 'A', text: 'How about a cartoon?', cn: '动画片怎么样？' },
      { speaker: 'B', text: 'Great! I love cartoons. What is the movie about?', cn: '太好了！我喜欢动画片。电影是关于什么的？' },
      { speaker: 'A', text: 'It is about a brave dog saving his friends.', cn: '是关于一只勇敢的狗救朋友的故事。' },
      { speaker: 'B', text: 'Sounds exciting! When should we go?', cn: '听起来很刺激！我们什么时候去？' },
      { speaker: 'A', text: 'How about this Saturday afternoon?', cn: '这个星期六下午怎么样？' },
      { speaker: 'B', text: 'Perfect! Which cinema should we go to?', cn: '太好了！我们应该去哪家电影院？' },
      { speaker: 'A', text: 'Let\'s go to the one near the park.', cn: '让我们去公园附近的那家。' },
      { speaker: 'B', text: 'Okay! I can\'t wait!', cn: '好的！我迫不及待了！' },
    ]
  },
  {
    title: '谈论运动',
    icon: '⚽',
    color: 'bg-green-100 dark:bg-green-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Do you like sports?', cn: '你喜欢运动吗？' },
      { speaker: 'B', text: 'Yes, I like playing basketball.', cn: '是的，我喜欢打篮球。' },
      { speaker: 'A', text: 'I like swimming. It is good exercise.', cn: '我喜欢游泳。这是很好的锻炼。' },
      { speaker: 'B', text: 'I want to learn swimming too!', cn: '我也想学游泳！' },
      { speaker: 'A', text: 'I can teach you! Do you have a pool near your home?', cn: '我可以教你！你家附近有游泳池吗？' },
      { speaker: 'B', text: 'Yes, there is a big pool in the sports center.', cn: '是的，体育中心有一个大游泳池。' },
      { speaker: 'A', text: 'That is perfect! We can go together.', cn: '那太完美了！我们可以一起去。' },
      { speaker: 'B', text: 'What about basketball? Can you teach me basketball?', cn: '那篮球呢？你能教我篮球吗？' },
      { speaker: 'A', text: 'I don\'t play basketball, but my brother does.', cn: '我不打篮球，但我哥哥打。' },
      { speaker: 'B', text: 'Cool! Maybe he can teach me too!', cn: '太酷了！也许他也能教我！' },
    ]
  },
  {
    title: '谈论音乐',
    icon: '🎵',
    color: 'bg-violet-100 dark:bg-violet-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Do you like music?', cn: '你喜欢音乐吗？' },
      { speaker: 'B', text: 'Yes! I like pop music.', cn: '喜欢！我喜欢流行音乐。' },
      { speaker: 'A', text: 'Can you play any instruments?', cn: '你会演奏乐器吗？' },
      { speaker: 'B', text: 'I can play the piano a little.', cn: '我会一点钢琴。' },
      { speaker: 'A', text: 'That is amazing! How long have you learned?', cn: '太神奇了！你学了多久？' },
      { speaker: 'B', text: 'I have learned for two years.', cn: '我学了两年了。' },
      { speaker: 'A', text: 'Can you play a song for me?', cn: '你能给我弹一首歌吗？' },
      { speaker: 'B', text: 'Sure! I will play "Happy Birthday" for you.', cn: '当然可以！我给你弹"生日快乐"。' },
      { speaker: 'A', text: 'Thank you! I love that song!', cn: '谢谢！我喜欢那首歌！' },
      { speaker: 'B', text: 'I hope you enjoy it. Here I go!', cn: '希望你喜欢。我开始弹了！' },
    ]
  },
  {
    title: '生日快乐',
    icon: '🎂',
    color: 'bg-pink-100 dark:bg-pink-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Happy birthday! This is for you.', cn: '生日快乐！这是给你的礼物。' },
      { speaker: 'B', text: 'Thank you so much! Can I open it?', cn: '非常感谢！我可以打开吗？' },
      { speaker: 'A', text: 'Yes, of course! I hope you like it.', cn: '当然可以！我希望你喜欢。' },
      { speaker: 'B', text: 'Wow! I love it! A new backpack!', cn: '哇！我好喜欢！一个新书包！' },
      { speaker: 'A', text: 'It is blue, your favorite color!', cn: '是蓝色的，你最喜欢的颜色！' },
      { speaker: 'B', text: 'How did you know I needed a new one?', cn: '你怎么知道我需要一个新的？' },
      { speaker: 'A', text: 'I saw your old one was broken.', cn: '我看到你的旧书包坏了。' },
      { speaker: 'B', text: 'You are so thoughtful! Thank you, my friend!', cn: '你真体贴！谢谢你，我的朋友！' },
      { speaker: 'A', text: 'You are welcome! Have a great birthday!', cn: '不客气！生日快乐！' },
      { speaker: 'B', text: 'I will use it every day at school!', cn: '我会在学校每天都用它！' },
    ]
  },
  {
    title: '生病',
    icon: '🤒',
    color: 'bg-slate-100 dark:bg-slate-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'You don\'t look well. What is wrong?', cn: '你看起来不太好。怎么了？' },
      { speaker: 'B', text: 'I have a headache and a fever.', cn: '我头疼而且发烧。' },
      { speaker: 'A', text: 'Oh no! You should see a doctor and rest.', cn: '哦不！你应该看医生并休息。' },
      { speaker: 'B', text: 'I think I will stay home today.', cn: '我想我今天会待在家里。' },
      { speaker: 'A', text: 'That is a good idea. Do you need medicine?', cn: '那是个好主意。你需要药吗？' },
      { speaker: 'B', text: 'Yes, I already took some medicine.', cn: '是的，我已经吃了一些药。' },
      { speaker: 'A', text: 'Do you need help with your homework?', cn: '你需要帮忙做作业吗？' },
      { speaker: 'B', text: 'Yes, can you bring me my homework?', cn: '是的，你能把我的作业带给我吗？' },
      { speaker: 'A', text: 'Of course! I will bring it after school.', cn: '当然可以！我放学后带给你。' },
      { speaker: 'B', text: 'Thank you for your care. I hope I get better soon.', cn: '谢谢你的关心。我希望我很快就好起来。' },
    ]
  },
  {
    title: '找失物',
    icon: '🔍',
    color: 'bg-amber-100 dark:bg-amber-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Did you see my red bag?', cn: '你看到我的红包了吗？' },
      { speaker: 'B', text: 'I think it is on your desk.', cn: '我觉得在你桌子上。' },
      { speaker: 'A', text: 'Oh, you are right! Thank you!', cn: '哦，你说得对！谢谢！' },
      { speaker: 'B', text: 'You are welcome! Be more careful next time.', cn: '不客气！下次要更小心。' },
      { speaker: 'A', text: 'I will. Where did you find it?', cn: '我会的。你在哪里找到的？' },
      { speaker: 'B', text: 'You left it in the classroom after lunch.', cn: '你午饭后把它忘在教室了。' },
      { speaker: 'A', text: 'I was so worried about losing it!', cn: '我太担心会弄丢它了！' },
      { speaker: 'B', text: 'Don\'t worry. Everything is fine now.', cn: '别担心。现在一切都好了。' },
      { speaker: 'A', text: 'Thank you for helping me find it!', cn: '谢谢你帮我找到它！' },
      { speaker: 'B', text: 'Anytime! We should always help each other!', cn: '随时！我们应该总是互相帮助！' },
    ]
  },
  {
    title: '图书馆',
    icon: '📖',
    color: 'bg-stone-100 dark:bg-stone-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'I want to borrow this book.', cn: '我想借这本书。' },
      { speaker: 'B', text: 'Let me check your library card.', cn: '让我查一下你的借书证。' },
      { speaker: 'A', text: 'Here is my card. How long can I keep it?', cn: '这是我的卡。我可以借多久？' },
      { speaker: 'B', text: 'Two weeks. Remember to return it on time.', cn: '两周。记得按时归还。' },
      { speaker: 'A', text: 'What happens if I return it late?', cn: '如果我晚还了会怎么样？' },
      { speaker: 'B', text: 'You will need to pay a small fine.', cn: '你需要付一小笔罚款。' },
      { speaker: 'A', text: 'I understand. Can I renew it if I need more time?', cn: '我明白了。如果需要更多时间可以续借吗？' },
      { speaker: 'B', text: 'Yes, you can renew it once for another two weeks.', cn: '可以的，你可以续借一次，再多两周。' },
      { speaker: 'A', text: 'Good to know. Here is the book.', cn: '很高兴知道。这是书。' },
      { speaker: 'B', text: 'Okay, you can take it now. Enjoy reading!', cn: '好的，你现在可以拿走了。享受阅读！' },
    ]
  },
  {
    title: '邮局',
    icon: '📮',
    color: 'bg-red-100 dark:bg-red-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'I want to send a letter to my friend.', cn: '我想给朋友寄一封信。' },
      { speaker: 'B', text: 'Where do you want to send it?', cn: '你想寄到哪里？' },
      { speaker: 'A', text: 'To Beijing. How much is the postage?', cn: '到北京。邮费是多少？' },
      { speaker: 'B', text: 'One yuan and twenty cents. Do you need an envelope?', cn: '一块两毛。你需要信封吗？' },
      { speaker: 'A', text: 'Yes, please. I don\'t have one.', cn: '是的，请给我一个。我没有信封。' },
      { speaker: 'B', text: 'Here is an envelope. That is two yuan total.', cn: '这是一个信封。总共两元。' },
      { speaker: 'A', text: 'When will the letter arrive?', cn: '信什么时候能到？' },
      { speaker: 'B', text: 'About three days. It is a regular letter.', cn: '大约三天。是普通信件。' },
      { speaker: 'A', text: 'Is there a faster option?', cn: '有更快的选择吗？' },
      { speaker: 'B', text: 'Yes, express mail takes one day, but it costs more.', cn: '有的，快递邮件一天就能到，但更贵。' },
    ]
  },
  {
    title: '理发店',
    icon: '💇',
    color: 'bg-gray-100 dark:bg-gray-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Welcome! How can I help you?', cn: '欢迎！我能帮你吗？' },
      { speaker: 'B', text: 'I want to get a haircut.', cn: '我想剪头发。' },
      { speaker: 'A', text: 'What style do you want?', cn: '你想要什么发型？' },
      { speaker: 'B', text: 'Just trim it a little shorter.', cn: '稍微剪短一点就好。' },
      { speaker: 'A', text: 'Okay. Do you want to wash your hair first?', cn: '好的。你想先洗头吗？' },
      { speaker: 'B', text: 'Yes, please. My hair is a bit dirty.', cn: '是的，请。我的头发有点脏。' },
      { speaker: 'A', text: 'Follow me to the wash area.', cn: '跟我去洗头区。' },
      { speaker: 'B', text: 'How much does a haircut cost?', cn: '剪头发多少钱？' },
      { speaker: 'A', text: 'It is 30 yuan for adults, 20 yuan for children.', cn: '成人30元，儿童20元。' },
      { speaker: 'B', text: 'That is reasonable. Let\'s start!', cn: '那很合理。让我们开始吧！' },
    ]
  },
  {
    title: '银行',
    icon: '🏦',
    color: 'bg-slate-100 dark:bg-slate-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'I would like to open a savings account.', cn: '我想开一个储蓄账户。' },
      { speaker: 'B', text: 'Please fill out this form first.', cn: '请先填写这张表格。' },
      { speaker: 'A', text: 'Do I need to show my ID card?', cn: '我需要出示身份证吗？' },
      { speaker: 'B', text: 'Yes, and provide your phone number.', cn: '是的，还要提供你的手机号。' },
      { speaker: 'A', text: 'Here is my ID and phone number.', cn: '这是我的身份证和手机号。' },
      { speaker: 'B', text: 'Thank you. How much would you like to deposit first?', cn: '谢谢。你首先想存多少钱？' },
      { speaker: 'A', text: 'I want to deposit 100 yuan.', cn: '我想存100元。' },
      { speaker: 'B', text: 'Okay. You will receive a bank card and passbook.', cn: '好的。你会收到银行卡和存折。' },
      { speaker: 'A', text: 'Can I use this card at ATMs?', cn: '我可以在ATM机使用这张卡吗？' },
      { speaker: 'B', text: 'Yes, you can withdraw money at any ATM.', cn: '可以的，你可以在任何ATM机取钱。' },
    ]
  },
  {
    title: '药店',
    icon: '💊',
    color: 'bg-emerald-100 dark:bg-emerald-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Excuse me, I need some medicine for a cold.', cn: '打扰一下，我需要一些感冒药。' },
      { speaker: 'B', text: 'Do you have a prescription?', cn: '你有处方吗？' },
      { speaker: 'A', text: 'No, I just have a runny nose and cough.', cn: '没有，我只是流鼻涕和咳嗽。' },
      { speaker: 'B', text: 'You can try this over-the-counter medicine.', cn: '你可以试试这种非处方药。' },
      { speaker: 'A', text: 'How should I take it?', cn: '我应该怎么吃？' },
      { speaker: 'B', text: 'Take one pill three times a day after meals.', cn: '饭后服用，一天三次，每次一片。' },
      { speaker: 'A', text: 'Are there any side effects?', cn: '有什么副作用吗？' },
      { speaker: 'B', text: 'You might feel a little sleepy. Don\'t drive after taking it.', cn: '你可能会感到有点困。吃药后不要开车。' },
      { speaker: 'A', text: 'How much is it?', cn: '多少钱？' },
      { speaker: 'B', text: 'It is 25 yuan. Here is your medicine.', cn: '25元。这是你的药。' },
    ]
  },
  {
    title: '谈论家庭',
    icon: '👨‍👩‍👧‍👦',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'How many people are there in your family?', cn: '你家有几口人？' },
      { speaker: 'B', text: 'There are four: my parents, my brother and me.', cn: '有四口：父母、哥哥和我。' },
      { speaker: 'A', text: 'What does your father do?', cn: '你爸爸是做什么的？' },
      { speaker: 'B', text: 'He is a doctor. He works at a hospital.', cn: '他是个医生。他在医院工作。' },
      { speaker: 'A', text: 'That is a great job! What about your mother?', cn: '那是个很棒的工作！你妈妈呢？' },
      { speaker: 'B', text: 'She is a teacher. She teaches English.', cn: '她是个老师。她教英语。' },
      { speaker: 'A', text: 'What about your brother?', cn: '你哥哥呢？' },
      { speaker: 'B', text: 'He is a student. He is in high school.', cn: '他是个学生。他在上高中。' },
      { speaker: 'A', text: 'You have a nice family! Do you get along well?', cn: '你有一个很好的家庭！你们相处得好吗？' },
      { speaker: 'B', text: 'Yes, we love each other very much!', cn: '是的，我们非常相爱！' },
    ]
  },
  {
    title: '谈论学校',
    icon: '🏫',
    color: 'bg-blue-100 dark:bg-blue-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Which school do you go to?', cn: '你在哪个学校上学？' },
      { speaker: 'B', text: 'I go to Star Primary School.', cn: '我在明星小学上学。' },
      { speaker: 'A', text: 'What is your favorite subject?', cn: '你最喜欢什么科目？' },
      { speaker: 'B', text: 'I like English and Math best.', cn: '我最喜欢英语和数学。' },
      { speaker: 'A', text: 'Why do you like English?', cn: '你为什么喜欢英语？' },
      { speaker: 'B', text: 'Because I want to travel around the world.', cn: '因为我想环游世界。' },
      { speaker: 'A', text: 'That is a great reason! What is your school like?', cn: '那是个很好的理由！你的学校怎么样？' },
      { speaker: 'B', text: 'My school is big and beautiful. I love it.', cn: '我的学校又大又美。我爱我的学校。' },
      { speaker: 'A', text: 'Do you have many friends at school?', cn: '你在学校有很多朋友吗？' },
      { speaker: 'B', text: 'Yes, my classmates are very friendly!', cn: '是的，我的同学很友好！' },
    ]
  },
  {
    title: '谈论老师',
    icon: '👨‍🏫',
    color: 'bg-purple-100 dark:bg-purple-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Who is your favorite teacher?', cn: '你最喜欢的老师是谁？' },
      { speaker: 'B', text: 'Mrs. Wang, she teaches English.', cn: '王老师，她教英语。' },
      { speaker: 'A', text: 'Why do you like her?', cn: '你为什么喜欢她？' },
      { speaker: 'B', text: 'She is very kind and patient.', cn: '她很善良也很耐心。' },
      { speaker: 'A', text: 'Does she make her classes interesting?', cn: '她的课有趣吗？' },
      { speaker: 'B', text: 'Yes! We play games and sing songs in class.', cn: '是的！我们在课上玩游戏、唱歌。' },
      { speaker: 'A', text: 'That sounds fun! What is your favorite class?', cn: '听起来很有趣！你最喜欢什么课？' },
      { speaker: 'B', text: 'I like Tuesday\'s class the most.', cn: '我最喜欢星期二的课。' },
      { speaker: 'A', text: 'Why Tuesday?', cn: '为什么是星期二？' },
      { speaker: 'B', text: 'Because we have a party on that day!', cn: '因为那天我们有一个派对！' },
    ]
  },
  {
    title: '谈论朋友',
    icon: '👫',
    color: 'bg-pink-100 dark:bg-pink-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Who is your best friend?', cn: '你最好的朋友是谁？' },
      { speaker: 'B', text: 'My best friend is Lisa.', cn: '我最好的朋友是丽莎。' },
      { speaker: 'A', text: 'What do you usually do together?', cn: '你们通常一起做什么？' },
      { speaker: 'B', text: 'We study together and play games.', cn: '我们一起学习和玩游戏。' },
      { speaker: 'A', text: 'How did you become friends?', cn: '你们怎么成为朋友的？' },
      { speaker: 'B', text: 'We met in first grade and have been friends since.', cn: '我们在一年级认识，从那时起就是朋友了。' },
      { speaker: 'A', text: 'That is a long friendship! Do you help each other?', cn: '那是一段很长的友谊！你们会互相帮助吗？' },
      { speaker: 'B', text: 'Yes! She helps me with math, I help her with English.', cn: '是的！她帮我学数学，我帮她学英语。' },
      { speaker: 'A', text: 'That is wonderful! Friends should support each other.', cn: '那太棒了！朋友应该互相支持。' },
      { speaker: 'B', text: 'I am lucky to have such a good friend!', cn: '我很幸运能有这么好的朋友！' },
    ]
  },
  {
    title: '谈论宠物',
    icon: '🐕',
    color: 'bg-amber-100 dark:bg-amber-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Do you have any pets?', cn: '你有宠物吗？' },
      { speaker: 'B', text: 'Yes, I have a dog. His name is Lucky.', cn: '有的，我有一只狗，它的名字叫幸运。' },
      { speaker: 'A', text: 'What does he look like?', cn: '它长什么样？' },
      { speaker: 'B', text: 'He is small and white with big eyes.', cn: '它很小，白色，有大眼睛。' },
      { speaker: 'A', text: 'Is he friendly? Does he like people?', cn: '它友好吗？它喜欢人吗？' },
      { speaker: 'B', text: 'Yes! He loves playing with children.', cn: '是的！它喜欢和孩子们一起玩。' },
      { speaker: 'A', text: 'What do you feed him?', cn: '你喂它吃什么？' },
      { speaker: 'B', text: 'Dog food and sometimes meat.', cn: '狗粮，有时还有肉。' },
      { speaker: 'A', text: 'Does he know any tricks?', cn: '它会什么技能吗？' },
      { speaker: 'B', text: 'Yes! He can sit and shake hands!', cn: '是的！它会坐下和握手！' },
    ]
  },
  {
    title: '谈论房间',
    icon: '🏠',
    color: 'bg-cyan-100 dark:bg-cyan-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What is your room like?', cn: '你的房间是什么样的？' },
      { speaker: 'B', text: 'It is small but very comfortable.', cn: '很小但是很舒服。' },
      { speaker: 'A', text: 'What color is your bed?', cn: '你的床是什么颜色的？' },
      { speaker: 'B', text: 'It is blue, my favorite color.', cn: '是蓝色的，我最喜欢的颜色。' },
      { speaker: 'A', text: 'Do you have a desk in your room?', cn: '你的房间有书桌吗？' },
      { speaker: 'B', text: 'Yes, I do my homework at my desk.', cn: '有的，我在书桌上做作业。' },
      { speaker: 'A', text: 'What is on your desk?', cn: '你的书桌上有什么？' },
      { speaker: 'B', text: 'Books, a lamp, and my pencil case.', cn: '书、台灯和我的铅笔盒。' },
      { speaker: 'A', text: 'Do you have any decorations?', cn: '你有什么装饰吗？' },
      { speaker: 'B', text: 'I have some pictures of my family and friends on the wall.', cn: '我在墙上挂了一些家人和朋友的照片。' },
    ]
  },
  {
    title: '谈论假期',
    icon: '🏖️',
    color: 'bg-teal-100 dark:bg-teal-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Where did you go for your holiday?', cn: '你假期去哪里了？' },
      { speaker: 'B', text: 'I went to the beach with my family.', cn: '我和家人去海边了。' },
      { speaker: 'A', text: 'That sounds great! What did you do there?', cn: '听起来很棒！你们在那里做了什么？' },
      { speaker: 'B', text: 'We swam in the sea and built sandcastles.', cn: '我们在海里游泳，堆沙堡。' },
      { speaker: 'A', text: 'Did you see any sea animals?', cn: '你看到任何海洋动物了吗？' },
      { speaker: 'B', text: 'Yes! We saw colorful fish and crabs.', cn: '看到了！我们看到了五颜六色的鱼和螃蟹。' },
      { speaker: 'A', text: 'Did you eat any seafood?', cn: '你吃了海鲜吗？' },
      { speaker: 'B', text: 'Yes, we had fresh fish and shrimp for dinner.', cn: '是的，我们晚餐吃了新鲜的鱼和虾。' },
      { speaker: 'A', text: 'How long did you stay there?', cn: '你们在那里待了多久？' },
      { speaker: 'B', text: 'We stayed for a week. I didn\'t want to leave!', cn: '我们待了一个星期。我不想离开！' },
    ]
  },
  {
    title: '谈论节日',
    icon: '🎄',
    color: 'bg-red-100 dark:bg-red-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What is your favorite festival?', cn: '你最喜欢的节日是什么？' },
      { speaker: 'B', text: 'I like Spring Festival the best.', cn: '我最喜欢春节。' },
      { speaker: 'A', text: 'What do you do on that day?', cn: '那天你们做什么？' },
      { speaker: 'B', text: 'We have dinner together and get red envelopes.', cn: '我们一起吃晚饭，还收红包。' },
      { speaker: 'A', text: 'That sounds fun! Do you eat special food?', cn: '听起来很有趣！你们吃特别的食物吗？' },
      { speaker: 'B', text: 'Yes, we eat dumplings and fish.', cn: '是的，我们吃饺子和鱼。' },
      { speaker: 'A', text: 'What about your family?', cn: '那你的家人呢？' },
      { speaker: 'B', text: 'My whole family comes to our house.', cn: '我的全家人都来我们家。' },
      { speaker: 'A', text: 'Do you watch fireworks?', cn: '你们看烟花吗？' },
      { speaker: 'B', text: 'Yes! We watch fireworks at midnight!', cn: '是的！我们在午夜看烟花！' },
    ]
  },
  {
    title: '谈论季节',
    icon: '🍂',
    color: 'bg-orange-100 dark:bg-orange-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'Which season do you like best?', cn: '你最喜欢哪个季节？' },
      { speaker: 'B', text: 'I like spring best.', cn: '我最喜欢春天。' },
      { speaker: 'A', text: 'Why do you like spring?', cn: '你为什么喜欢春天？' },
      { speaker: 'B', text: 'Because the flowers bloom and it is warm.', cn: '因为花开而且很温暖。' },
      { speaker: 'A', text: 'What do you like to do in spring?', cn: '春天你喜欢做什么？' },
      { speaker: 'B', text: 'I like to fly kites and go hiking.', cn: '我喜欢放风筝和徒步旅行。' },
      { speaker: 'A', text: 'What about other seasons?', cn: '其他季节呢？' },
      { speaker: 'B', text: 'I don\'t like summer because it is too hot.', cn: '我不喜欢夏天，因为太热了。' },
      { speaker: 'A', text: 'What about winter?', cn: '那冬天呢？' },
      { speaker: 'B', text: 'Winter is cold but I like playing in the snow!', cn: '冬天很冷，但我喜欢在雪地里玩！' },
    ]
  },
  {
    title: '谈论时间',
    icon: '⏰',
    color: 'bg-indigo-100 dark:bg-indigo-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What time do you get up every day?', cn: '你每天几点起床？' },
      { speaker: 'B', text: 'I get up at 7 o\'clock.', cn: '我7点起床。' },
      { speaker: 'A', text: 'What time do you go to bed?', cn: '你几点睡觉？' },
      { speaker: 'B', text: 'I go to bed at 9 o\'clock.', cn: '我9点睡觉。' },
      { speaker: 'A', text: 'What do you do after you get up?', cn: '你起床后做什么？' },
      { speaker: 'B', text: 'I brush my teeth and wash my face.', cn: '我刷牙洗脸。' },
      { speaker: 'A', text: 'Then what do you do?', cn: '然后你做什么？' },
      { speaker: 'B', text: 'I eat breakfast and go to school.', cn: '我吃早饭然后去上学。' },
      { speaker: 'A', text: 'What about after school?', cn: '放学后呢？' },
      { speaker: 'B', text: 'I do my homework and then play games.', cn: '我做作业，然后玩游戏。' },
    ]
  },
  {
    title: '谈论日程',
    icon: '📋',
    color: 'bg-slate-100 dark:bg-slate-900',
    level: 2,
    scenario: [
      { speaker: 'A', text: 'What do you do on weekends?', cn: '你周末做什么？' },
      { speaker: 'B', text: 'I do my homework in the morning.', cn: '我早上做作业。' },
      { speaker: 'A', text: 'What about the afternoon?', cn: '下午呢？' },
      { speaker: 'B', text: 'I play with my friends.', cn: '我和朋友一起玩。' },
      { speaker: 'A', text: 'What do you play?', cn: '你们玩什么？' },
      { speaker: 'B', text: 'We play football or go to the park.', cn: '我们踢足球或去公园。' },
      { speaker: 'A', text: 'What about Sunday?', cn: '星期日呢？' },
      { speaker: 'B', text: 'On Sunday, I visit my grandparents.', cn: '星期日，我看望祖父母。' },
      { speaker: 'A', text: 'That sounds nice! Do you have a busy weekend?', cn: '听起来很棒！你周末忙吗？' },
      { speaker: 'B', text: 'A little busy, but I enjoy my weekend!', cn: '有点忙，但我很享受我的周末！' },
    ]
  },
];

// 由于对话内容太多，我会继续添加Level 3-5的对话...
// 注意：为了节省空间，这里只展示部分对话，实际实现时需要全部200个对话

// 按难度级别分组对话
export const dialoguesByLevel = {
  1: dialogues.filter(d => d.level === 1),
  2: dialogues.filter(d => d.level === 2),
  3: dialogues.filter(d => d.level === 3),
  4: dialogues.filter(d => d.level === 4),
  5: dialogues.filter(d => d.level === 5),
};

// 获取难度级别的描述
export const getLevelDescription = (level: number): string => {
  const descriptions = {
    1: 'Level 1 - 基础入门',
    2: 'Level 2 - 日常交流',
    3: 'Level 3 - 场景对话',
    4: 'Level 4 - 社会场景',
    5: 'Level 5 - 高级讨论',
  };
  return descriptions[level as keyof typeof descriptions] || '';
};
