export interface Story {
  id: string;
  title: string;
  titleCn: string;
  content: string[];
  level: number; // 1-5 难度级别
  category: 'story';
  tags: string[];
  bgGradient: string;
  icon: string;
}

export const stories: Story[] = [
  {
    id: 'three-pigs',
    title: 'The Three Little Pigs',
    titleCn: '三只小猪',
    content: [
      'Once upon a time, there were three little pigs.',
      'They left home to build their own houses.',
      '',
      'The first pig built a house of straw.',
      'The second pig built a house of sticks.',
      'The third pig built a house of bricks.',
      '',
      'A big bad wolf came to eat the pigs.',
      'He blew down the straw house!',
      'The first pig ran to the stick house.',
      '',
      'The wolf blew down the stick house too!',
      'Both pigs ran to the brick house.',
      '',
      'The wolf huffed and puffed,',
      'But he could not blow down the brick house.',
      'The three little pigs were safe.',
      '',
      'The moral: Work hard and build well.'
    ],
    level: 2,
    category: 'story',
    tags: ['猪', '努力', '童话'],
    bgGradient: 'from-pink-100 via-rose-100 to-red-100',
    icon: '🐷'
  },
  {
    id: 'goldilocks',
    title: 'Goldilocks and the Three Bears',
    titleCn: '金发姑娘和三只熊',
    content: [
      'Goldilocks was walking in the forest.',
      'She found a little house.',
      '',
      'Inside, there were three bowls of porridge.',
      'The big bowl was too hot.',
      'The medium bowl was too cold.',
      'The small bowl was just right!',
      'She ate it all up.',
      '',
      'Then she saw three chairs.',
      'The big chair was too hard.',
      'The medium chair was too soft.',
      'The small chair was just right!',
      'But she broke it!',
      '',
      'Upstairs, she found three beds.',
      'She fell asleep in the small bed.',
      '',
      'The three bears came home.',
      'They saw the empty bowls and broken chair.',
      'They found Goldilocks asleep.',
      'She woke up and ran away!'
    ],
    level: 3,
    category: 'story',
    tags: ['熊', '女孩', '童话'],
    bgGradient: 'from-amber-100 via-orange-100 to-yellow-100',
    icon: '🐻'
  },
  {
    id: 'red-riding',
    title: 'Little Red Riding Hood',
    titleCn: '小红帽',
    content: [
      'Once there was a girl named Little Red Riding Hood.',
      'She loved her grandma very much.',
      '',
      'Her mom gave her a basket of food.',
      '"Take this to Grandma," she said.',
      '"But stay on the path!"',
      '',
      'Little Red walked through the forest.',
      'A wolf came to her.',
      '"Where are you going?" asked the wolf.',
      '"To my grandma\'s house," she said.',
      '',
      'The wolf ran ahead to Grandma\'s house.',
      'He ate Grandma and got into her bed.',
      '',
      'When Little Red arrived, the wolf tried to eat her too!',
      'But a woodcutter came and saved them.',
      'They were happy and safe.'
    ],
    level: 3,
    category: 'story',
    tags: ['狼', '女孩', '童话'],
    bgGradient: 'from-red-100 via-pink-100 to-rose-100',
    icon: '🔴'
  },
  {
    id: 'cinderella',
    title: 'Cinderella',
    titleCn: '灰姑娘',
    content: [
      'Cinderella lived with her stepmother and stepsisters.',
      'They made her work hard all day.',
      'She was very sad.',
      '',
      'One day, the prince invited everyone to a ball.',
      'Cinderella wanted to go.',
      'But her stepsisters would not let her.',
      '',
      'Suddenly, her fairy godmother appeared!',
      'She turned a pumpkin into a coach.',
      'She turned mice into horses.',
      'She gave Cinderella a beautiful dress.',
      'And glass slippers!',
      '',
      '"But come home by midnight," said the fairy.',
      'Or the magic would end.',
      '',
      'At the ball, the prince fell in love with Cinderella.',
      'They danced all night.',
      'Suddenly, the clock struck twelve!',
      'Cinderella ran away, losing one glass slipper.',
      '',
      'The prince found the slipper.',
      'He searched everywhere for the girl who fit it.',
      'Finally, he found Cinderella.',
      'They married and lived happily ever after.'
    ],
    level: 4,
    category: 'story',
    tags: ['公主', '魔法', '童话'],
    bgGradient: 'from-blue-100 via-indigo-100 to-purple-100',
    icon: '👠'
  },
  {
    id: 'tortoise-hare',
    title: 'The Tortoise and the Hare',
    titleCn: '龟兔赛跑',
    content: [
      'The hare was very proud of his speed.',
      '"I am the fastest animal," he said.',
      '',
      'The tortoise was slow but steady.',
      '"Let\'s have a race," said the tortoise.',
      '',
      'The hare laughed.',
      '"You will never beat me!"',
      '',
      'The race began.',
      'The hare ran very fast.',
      'He was far ahead.',
      '',
      '"I have time to rest," said the hare.',
      'He fell asleep under a tree.',
      '',
      'The tortoise kept walking slowly.',
      'He never stopped.',
      '',
      'The hare woke up and saw the tortoise near the finish line.',
      'He ran as fast as he could.',
      'But it was too late!',
      '',
      'The tortoise won the race.',
      '',
      'The moral: Slow and steady wins the race.'
    ],
    level: 2,
    category: 'story',
    tags: ['龟', '兔', '寓言'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🐢'
  },
  {
    id: 'sleeping-beauty',
    title: 'Sleeping Beauty',
    titleCn: '睡美人',
    content: [
      'Once upon a time, a king and queen had a baby girl.',
      'They named her Aurora.',
      '',
      'They invited fairies to her party.',
      'But they forgot one evil fairy.',
      'She was very angry!',
      '',
      'She cast a spell on Aurora.',
      '"On her sixteenth birthday, she will prick her finger and die."',
      '',
      'The good fairy changed the spell.',
      'Aurora would not die, but sleep for a hundred years.',
      '',
      'The king burned all the spinning wheels.',
      'But on her sixteenth birthday, Aurora found a spinning wheel.',
      'She pricked her finger and fell asleep.',
      '',
      'The whole castle fell asleep too.',
      'A forest grew around it.',
      '',
      'Many years later, a prince came.',
      'He kissed Aurora.',
      'She woke up, and the whole castle woke up too.',
      '',
      'They lived happily ever after.'
    ],
    level: 4,
    category: 'story',
    tags: ['公主', '睡眠', '童话'],
    bgGradient: 'from-pink-100 via-rose-100 to-purple-100',
    icon: '💤'
  },
  {
    id: 'ugly-duckling',
    title: 'The Ugly Duckling',
    titleCn: '丑小鸭',
    content: [
      'A duck laid eggs in the grass.',
      'One egg was bigger than the others.',
      '',
      'When the eggs hatched, one duckling looked different.',
      'He was big and gray.',
      'The other ducklings laughed at him.',
      '',
      '"You are so ugly!" they said.',
      'The ugly duckling was very sad.',
      'He ran away.',
      '',
      'He lived with ducks, geese, and chickens.',
      'But no one wanted him.',
      '',
      'Winter came and it was very cold.',
      'The ugly duckling was lonely.',
      '',
      'Then spring came.',
      'The ugly duckling saw some beautiful swans.',
      'He wanted to be like them.',
      '',
      'He looked at his reflection in the water.',
      'He was not a duck!',
      'He was a beautiful swan!',
      '',
      'The other swans welcomed him.',
      'He was the happiest swan in the world.',
      '',
      'The moral: Beauty comes from within.'
    ],
    level: 3,
    category: 'story',
    tags: ['鸭子', '天鹅', '成长'],
    bgGradient: 'from-blue-100 via-cyan-100 to-teal-100',
    icon: '🦢'
  },
  {
    id: 'hansel-gretel',
    title: 'Hansel and Gretel',
    titleCn: '韩赛尔与格蕾特',
    content: [
      'Hansel and Gretel were poor brother and sister.',
      'Their stepmother left them in the forest.',
      '',
      'They found a house made of candy and cake!',
      'They started to eat it.',
      '',
      'An old witch lived there.',
      'She trapped them in a cage.',
      'She wanted to eat them!',
      '',
      'The witch checked Hansel\'s finger every day.',
      'He gave her a bone, not his finger.',
      'She thought he was still thin.',
      '',
      'One day, the witch got tired of waiting.',
      'She wanted to bake Gretel.',
      '',
      'Gretel pushed the witch into the oven!',
      'She freed Hansel.',
      'They found the witch\'s treasure and went home.',
      '',
      'Their father was so happy to see them.',
      'They never went hungry again.'
    ],
    level: 4,
    category: 'story',
    tags: ['兄妹', '巫婆', '童话'],
    bgGradient: 'from-amber-100 via-yellow-100 to-orange-100',
    icon: '🍬'
  },
  {
    id: 'little-mermaid',
    title: 'The Little Mermaid',
    titleCn: '小美人鱼',
    content: [
      'Deep in the ocean lived a little mermaid.',
      'She wanted to see the world above.',
      '',
      'On her fifteenth birthday, she swam to the surface.',
      'She saw a ship and a handsome prince.',
      'She fell in love with him.',
      '',
      'A storm came and the prince fell into the sea.',
      'The mermaid saved him and brought him to shore.',
      '',
      'She wanted to be with him on land.',
      'She went to the sea witch for help.',
      '',
      'The witch gave her legs but took her voice.',
      '"If he marries someone else, you will turn into sea foam."',
      '',
      'The prince found her but did not know she saved him.',
      'He married another princess.',
      '',
      'The mermaid\'s sisters gave her a magic knife.',
      '"Kill the prince and you can be a mermaid again."',
      '',
      'But she loved the prince too much.',
      'She threw the knife into the sea.',
      'She turned into sea foam but became an air spirit.',
      '',
      'The moral: True love is selfless.'
    ],
    level: 5,
    category: 'story',
    tags: ['美人鱼', '爱情', '童话'],
    bgGradient: 'from-blue-100 via-cyan-100 to-teal-100',
    icon: '🧜‍♀️'
  },
  {
    id: 'snow-white',
    title: 'Snow White',
    titleCn: '白雪公主',
    content: [
      'Once upon a time, there was a princess named Snow White.',
      'Her skin was as white as snow.',
      'Her lips were as red as blood.',
      'Her hair was as black as night.',
      '',
      'Her stepmother, the queen, was very jealous.',
      'The magic mirror said Snow White was the fairest.',
      '',
      'The queen ordered a hunter to kill Snow White.',
      'But the hunter let her go.',
      '',
      'Snow White found a little house in the forest.',
      'Seven dwarfs lived there.',
      'They welcomed her.',
      '',
      'The queen found out Snow White was alive.',
      'She made a poisoned apple.',
      '',
      'She tricked Snow White into eating it.',
      'Snow White fell into a deep sleep.',
      '',
      'The dwarfs were heartbroken.',
      'They put her in a glass coffin.',
      '',
      'A prince came and saw Snow White.',
      'He kissed her, and she woke up!',
      '',
      'They got married and lived happily ever after.'
    ],
    level: 4,
    category: 'story',
    tags: ['公主', '苹果', '童话'],
    bgGradient: 'from-white via-blue-50 to-cyan-50',
    icon: '🍎'
  },
  {
    id: 'frog-prince',
    title: 'The Frog Prince',
    titleCn: '青蛙王子',
    content: [
      'A princess was playing with her golden ball.',
      'It fell into a pond.',
      '',
      'A frog appeared.',
      '"I will get your ball if you promise to be my friend."',
      '',
      'The princess agreed but did not mean it.',
      'The frog returned the ball.',
      '',
      'The next day, the frog came to the castle.',
      'The princess did not want him.',
      'But the king made her keep her promise.',
      '',
      'The frog ate from her plate and slept in her bed.',
      'The princess was disgusted.',
      '',
      'She threw the frog against the wall!',
      '',
      'Suddenly, the frog turned into a handsome prince!',
      'He had been under a curse.',
      'The princess broke the curse.',
      '',
      'They fell in love and married.',
      '',
      'The moral: Keep your promises.'
    ],
    level: 3,
    category: 'story',
    tags: ['青蛙', '王子', '童话'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🐸'
  },
  {
    id: 'rapunzel',
    title: 'Rapunzel',
    titleCn: '长发公主',
    content: [
      'A witch stole a couple\'s baby daughter.',
      'She named her Rapunzel.',
      'She locked her in a tall tower.',
      '',
      'Rapunzel had very long golden hair.',
      'The witch climbed up using her hair.',
      '"Rapunzel, Rapunzel, let down your hair!"',
      '',
      'One day, a prince heard Rapunzel singing.',
      'He fell in love with her voice.',
      '',
      'He discovered how to climb the tower.',
      'He visited Rapunzel every day.',
      'They fell in love.',
      '',
      'The witch found out.',
      'She cut off Rapunzel\'s hair and sent her away.',
      '',
      'When the prince came, the witch pushed him out the window.',
      'He fell into thorns and became blind.',
      '',
      'For years, the prince wandered alone.',
      'One day, he heard Rapunzel singing.',
      'Her tears cured his blindness.',
      '',
      'They returned to his kingdom and married.'
    ],
    level: 4,
    category: 'story',
    tags: ['公主', '长发', '童话'],
    bgGradient: 'from-yellow-100 via-amber-100 to-orange-100',
    icon: '👸'
  },
  {
    id: 'aladdin',
    title: 'Aladdin',
    titleCn: '阿拉丁',
    content: [
      'Aladdin was a poor boy in a faraway land.',
      'A magician found him and asked for help.',
      '',
      'He took Aladdin to a cave full of treasure.',
      '"Bring me the magic lamp," said the magician.',
      '',
      'Aladdin found the lamp but refused to give it.',
      'The magician closed the cave and left him trapped!',
      '',
      'Aladdin rubbed the lamp.',
      'A genie appeared!',
      '"I will grant you three wishes," said the genie.',
      '',
      'Aladdin wished to escape the cave.',
      'Then he wished to be a prince.',
      'He wanted to marry Princess Jasmine.',
      '',
      'The magician stole the lamp.',
      'He became powerful and captured Jasmine.',
      '',
      'Aladdin found the magician and took back the lamp.',
      'He saved Jasmine.',
      '',
      'His third wish was to free the genie.',
      'Aladdin and Jasmine married and ruled together.'
    ],
    level: 4,
    category: 'story',
    tags: ['魔法', '王子', '冒险'],
    bgGradient: 'from-blue-100 via-indigo-100 to-purple-100',
    icon: '🪔'
  },
  {
    id: 'lion-mouse',
    title: 'The Lion and the Mouse',
    titleCn: '狮子和老鼠',
    content: [
      'A lion was sleeping in the forest.',
      'A little mouse ran across his nose.',
      '',
      'The lion woke up and caught the mouse.',
      '"Please let me go!" begged the mouse.',
      '"Someday I will help you."',
      '',
      'The lion laughed.',
      '"You are too small to help me!"',
      'But he let the mouse go.',
      '',
      'One day, the lion was caught in a hunter\'s net.',
      'He roared and struggled, but could not escape.',
      '',
      'The mouse heard the lion\'s roar.',
      'He ran to help.',
      '',
      'The mouse chewed through the ropes.',
      'The lion was free!',
      '',
      '"Thank you, little friend," said the lion.',
      '"Even a small mouse can help a big lion."',
      '',
      'The moral: No act of kindness is ever wasted.'
    ],
    level: 2,
    category: 'story',
    tags: ['狮子', '老鼠', '寓言'],
    bgGradient: 'from-amber-100 via-orange-100 to-yellow-100',
    icon: '🦁'
  },
  {
    id: 'ant-grasshopper',
    title: 'The Ant and the Grasshopper',
    titleCn: '蚂蚁和蚱蜢',
    content: [
      'In summer, a grasshopper played all day.',
      'He sang and danced in the sun.',
      '',
      'An ant worked hard gathering food.',
      '"Why do you work so hard?" asked the grasshopper.',
      '"Winter is coming," said the ant.',
      '',
      'The grasshopper laughed.',
      '"There is plenty of food now!"',
      'He kept playing.',
      '',
      'Winter came and it was very cold.',
      'The snow covered the ground.',
      '',
      'The grasshopper was hungry.',
      'He had no food.',
      '',
      'He went to the ant\'s house.',
      '"Please give me some food!"',
      '',
      'The ant shared his food with him.',
      '"Next time, prepare for winter," he said.',
      '',
      'The moral: Work today to eat tomorrow.'
    ],
    level: 2,
    category: 'story',
    tags: ['蚂蚁', '蚱蜢', '寓言'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🐜'
  },
  {
    id: 'city-mouse-country',
    title: 'The City Mouse and the Country Mouse',
    titleCn: '城里老鼠和乡下老鼠',
    content: [
      'The country mouse lived in a simple house.',
      'He ate beans and corn every day.',
      '',
      'One day, the city mouse came to visit.',
      '"My friend, you live poorly!" he said.',
      '"Come with me to the city."',
      '',
      'They went to the city.',
      'The city mouse lived in a grand house.',
      'There was cake, cheese, and wine!',
      '',
      'But suddenly, a cat appeared!',
      'They had to hide in a hole.',
      '',
      'Then big dogs came!',
      'They were scared again.',
      '',
      '"I\'m going home," said the country mouse.',
      '"I\'d rather eat simple food in peace than rich food in danger."',
      '',
      'The moral: Better safe than sorry.'
    ],
    level: 3,
    category: 'story',
    tags: ['老鼠', '城市', '寓言'],
    bgGradient: 'from-gray-100 via-slate-100 to-zinc-100',
    icon: '🐭'
  },
  {
    id: 'north-wind-sun',
    title: 'The North Wind and the Sun',
    titleCn: '北风和太阳',
    content: [
      'The North Wind and the Sun argued.',
      '"I am stronger," said the North Wind.',
      '"No, I am stronger," said the Sun.',
      '',
      'They saw a traveler in a coat.',
      '"Let\'s see who can make him take off his coat."',
      '',
      'The North Wind went first.',
      'He blew as hard as he could.',
      'The traveler held his coat tighter.',
      '',
      'The North Wind blew harder and harder.',
      'The traveler held his coat even tighter!',
      '',
      'The North Wind gave up.',
      '"Now it\'s my turn," said the Sun.',
      '',
      'The Sun shone gently.',
      'The traveler felt warm.',
      'He loosened his coat.',
      '',
      'The Sun shone brighter.',
      'The traveler felt hot.',
      'He took off his coat!',
      '',
      'The moral: Kindness is stronger than force.'
    ],
    level: 2,
    category: 'story',
    tags: ['自然', '比赛', '寓言'],
    bgGradient: 'from-yellow-100 via-orange-100 to-red-100',
    icon: '☀️'
  },
  {
    id: 'boy-wolf',
    title: 'The Boy Who Cried Wolf',
    titleCn: '狼来了',
    content: [
      'A shepherd boy watched sheep every day.',
      'It was boring.',
      '',
      'One day, he had an idea.',
      'He shouted, "Wolf! Wolf! Help!"',
      '',
      'The villagers came running.',
      '"Where is the wolf?" they asked.',
      'The boy laughed. "There is no wolf!"',
      '',
      'The villagers were angry.',
      'They went back to work.',
      '',
      'The next day, the boy did it again.',
      '"Wolf! Wolf!"',
      'The villagers came running.',
      'He laughed at them again.',
      '',
      'One day, a real wolf came!',
      'The boy shouted, "Wolf! Wolf! Help!"',
      '',
      'The villagers heard him.',
      '"He\'s lying again," they said.',
      'No one came.',
      '',
      'The wolf ate all the sheep.',
      '',
      'The moral: No one believes a liar even when he tells the truth.'
    ],
    level: 2,
    category: 'story',
    tags: ['谎言', '后果', '寓言'],
    bgGradient: 'from-gray-100 via-slate-100 to-zinc-100',
    icon: '🐺'
  },
  {
    id: 'midsummer-night',
    title: 'A Midsummer Night\'s Dream',
    titleCn: '仲夏夜之梦',
    content: [
      'In Athens, four young lovers ran into the forest.',
      'Hermia loved Lysander but had to marry Demetrius.',
      'Helena loved Demetrius but he loved Hermia.',
      '',
      'Fairies lived in the forest too.',
      'Oberon and Titania were the fairy king and queen.',
      '',
      'Puck, a mischievous fairy, played tricks.',
      'He put magic juice in people\'s eyes.',
      'They fell in love with the first person they saw.',
      '',
      'Lysander fell in love with Helena.',
      'Demetrius fell in love with Helena too!',
      'Hermia was confused and angry.',
      '',
      'Puck also turned a man named Bottom into a donkey.',
      'Titania fell in love with the donkey!',
      '',
      'By morning, Puck fixed everything.',
      'The lovers found their true partners.',
      'Lysander and Hermia married.',
      'Demetrius and Helena married.',
      '',
      'They all lived happily ever after.'
    ],
    level: 5,
    category: 'story',
    tags: ['爱情', '魔法', '喜剧'],
    bgGradient: 'from-purple-100 via-indigo-100 to-blue-100',
    icon: '🌙'
  },
  {
    id: 'beauty-beast',
    title: 'Beauty and the Beast',
    titleCn: '美女与野兽',
    content: [
      'A merchant had three daughters.',
      'The youngest was named Beauty.',
      '',
      'One day, the merchant got lost.',
      'He found a magical castle.',
      'He picked a rose for Beauty.',
      '',
      'A Beast appeared.',
      '"You stole my rose! Send your daughter here!"',
      '',
      'Beauty went to the castle to save her father.',
      'She was afraid of the Beast.',
      '',
      'But the Beast was kind.',
      'They became friends.',
      'Beauty saw his kind heart.',
      '',
      'She visited her family.',
      'She stayed too long.',
      '',
      'The Beast was dying of a broken heart.',
      'Beauty returned and found him.',
      '"I love you," she said.',
      '',
      'The Beast turned into a handsome prince!',
      'He had been under a curse.',
      'Beauty broke the spell.',
      '',
      'They married and lived happily ever after.',
      '',
      'The moral: True beauty comes from within.'
    ],
    level: 4,
    category: 'story',
    tags: ['公主', '野兽', '爱情'],
    bgGradient: 'from-rose-100 via-pink-100 to-red-100',
    icon: '🌹'
  },
  {
    id: 'peter-pan',
    title: 'Peter Pan',
    titleCn: '彼得·潘',
    content: [
      'Peter Pan was a boy who never grew up.',
      'He lived in a magical place called Neverland.',
      '',
      'One night, Peter visited the Darling family.',
      'He lost his shadow.',
      'Wendy Darling helped him reattach it.',
      '',
      'Peter sprinkled magic dust on Wendy and her brothers.',
      'They flew to Neverland!',
      '',
      'In Neverland, they met the Lost Boys.',
      'They fought pirates led by Captain Hook.',
      '',
      'Captain Hook wanted to kill Peter Pan.',
      'Peter defeated him with his courage.',
      '',
      'Wendy and her brothers stayed for a long time.',
      'But they missed their parents.',
      '',
      'Peter took them home.',
      'Wendy grew up and had her own children.',
      '',
      'But Peter Pan never forgot his friend Wendy.',
      'He still lives in Neverland, never growing up.'
    ],
    level: 4,
    category: 'story',
    tags: ['飞翔', '海盗', '冒险'],
    bgGradient: 'from-green-100 via-teal-100 to-blue-100',
    icon: '🧚'
  },
  {
    id: 'alice-wonderland',
    title: 'Alice in Wonderland',
    titleCn: '爱丽丝梦游仙境',
    content: [
      'Alice was sitting by a river with her sister.',
      'Suddenly, a white rabbit ran past.',
      '"I\'m late! I\'m late!" the rabbit said.',
      'It was wearing a watch!',
      '',
      'Alice followed the rabbit down a rabbit hole.',
      'She fell and fell and fell.',
      '',
      'She landed in a strange world.',
      'Everything was curious and odd.',
      '',
      'She drank a potion and became small.',
      'She ate a cake and became big.',
      '',
      'She met a Cheshire Cat who could disappear.',
      'She had tea with the Mad Hatter.',
      'She played croquet with the Queen of Hearts.',
      '',
      '"Off with her head!" the Queen shouted.',
      'But Alice was not afraid.',
      '',
      'Suddenly, Alice woke up.',
      'It was all a dream!',
      'But she would never forget Wonderland.'
    ],
    level: 4,
    category: 'story',
    tags: ['梦境', '奇幻', '冒险'],
    bgGradient: 'from-purple-100 via-pink-100 to-red-100',
    icon: '🐇'
  },
  {
    id: 'wizard-oz',
    title: 'The Wizard of Oz',
    titleCn: '绿野仙踪',
    content: [
      'Dorothy lived in Kansas with her dog Toto.',
      'A tornado carried her house to a magical land called Oz.',
      '',
      'Her house landed on the Wicked Witch of the East.',
      'The Good Witch gave Dorothy magical ruby slippers.',
      '',
      '"Follow the yellow brick road to find the Wizard," she said.',
      '"He can help you go home."',
      '',
      'Dorothy met a scarecrow who wanted a brain.',
      'She met a tin man who wanted a heart.',
      'She met a lion who wanted courage.',
      '',
      'They all went to find the Wizard together.',
      'They faced many adventures.',
      '',
      'The Wicked Witch of the West tried to stop them.',
      'But Dorothy defeated her.',
      '',
      'The Wizard gave them what they wanted.',
      'He told Dorothy the slippers could take her home.',
      '',
      'She clicked her heels three times.',
      '"There\'s no place like home."',
      'She returned to Kansas safely.'
    ],
    level: 4,
    category: 'story',
    tags: ['魔法', '友谊', '冒险'],
    bgGradient: 'from-emerald-100 via-green-100 to-teal-100',
    icon: '👠'
  },
  {
    id: 'thumbelina',
    title: 'Thumbelina',
    titleCn: '拇指姑娘',
    content: [
      'A woman wanted a child.',
      'A fairy gave her a barley seed.',
      '',
      'She planted the seed.',
      'A beautiful flower grew.',
      'Inside was a tiny girl no bigger than a thumb.',
      'They called her Thumbelina.',
      '',
      'One night, a toad stole her away.',
      'He wanted her to marry his son.',
      'Thumbelina was very sad.',
      '',
      'A fish helped her escape.',
      'A butterfly carried her across the water.',
      '',
      'A beetle took her to his home.',
      'But the other beetles thought she was ugly.',
      'He let her go.',
      '',
      'Thumbelina lived alone in the forest.',
      'Winter came and she was cold.',
      '',
      'A mouse let her stay in her home.',
      'But she had to marry a mole she did not love.',
      '',
      'Thumbelina found a sick swallow in the tunnel.',
      'She nursed him back to health.',
      '',
      'The swallow took her to a flower garden.',
      'There she met flower princes.',
      'She married the flower prince.',
      '',
      'She got wings and lived happily ever after.'
    ],
    level: 4,
    category: 'story',
    tags: ['小人', '童话', '冒险'],
    bgGradient: 'from-pink-100 via-rose-100 to-purple-100',
    icon: '🌸'
  },
  {
    id: 'emperor-clothes',
    title: 'The Emperor\'s New Clothes',
    titleCn: '皇帝的新衣',
    content: [
      'An emperor loved fine clothes.',
      'Two weavers came to the city.',
      '',
      '"We can make you magical clothes," they said.',
      '"Only wise people can see them."',
      '',
      'The weavers pretended to weave.',
      'But the looms were empty!',
      '',
      'The emperor could not see any clothes.',
      'But he was afraid to look foolish.',
      '"They are beautiful!" he said.',
      '',
      'The weavers asked for more money.',
      'They pretended to make the clothes.',
      '',
      'The emperor put on the invisible clothes.',
      'Everyone praised them.',
      'No one wanted to seem foolish.',
      '',
      'The emperor walked through the city.',
      'People cheered for his beautiful clothes.',
      '',
      'A little child watched.',
      '"But he isn\'t wearing anything!" the child said.',
      '',
      'Everyone started laughing.',
      'The emperor realized he had been tricked.',
      '',
      'The moral: We should always speak the truth.'
    ],
    level: 3,
    category: 'story',
    tags: ['皇帝', '诚实', '讽刺'],
    bgGradient: 'from-purple-100 via-indigo-100 to-blue-100',
    icon: '👑'
  },
  {
    id: 'pinocchio',
    title: 'Pinocchio',
    titleCn: '匹诺曹',
    content: [
      'Geppetto was a poor woodcarver.',
      'He made a wooden puppet and named him Pinocchio.',
      '',
      'A fairy made the puppet come alive!',
      '"You must be brave, truthful, and unselfish," she said.',
      '"Then you will become a real boy."',
      '',
      'Pinocchio made many mistakes.',
      'He lied to his father.',
      'Every time he lied, his nose grew longer!',
      '',
      'A fox and a cat tricked him.',
      'They stole his money.',
      '',
      'Pinocchio jumped into the sea to save his father.',
      'He was swallowed by a whale!',
      '',
      'In the whale\'s belly, he found Geppetto.',
      'They escaped together.',
      '',
      'Pinocchio worked hard and helped others.',
      'He told the truth.',
      '',
      'The fairy appeared again.',
      'She turned him into a real boy!',
      '',
      'Pinocchio and Geppetto lived happily ever after.'
    ],
    level: 3,
    category: 'story',
    tags: ['木偶', '诚实', '成长'],
    bgGradient: 'from-amber-100 via-orange-100 to-yellow-100',
    icon: '🤥'
  },
  {
    id: 'gingerbread-man',
    title: 'The Gingerbread Man',
    titleCn: '姜饼人',
    content: [
      'An old woman made a gingerbread man.',
      'She put him in the oven to bake.',
      '',
      'When she opened the oven, the Gingerbread Man jumped out!',
      '"Run, run, as fast as you can!"',
      '"You can\'t catch me, I\'m the Gingerbread Man!"',
      '',
      'He ran past the old woman.',
      '"Catch me!" he called.',
      '',
      'He ran past a cow.',
      '"Catch me!" he called.',
      '',
      'He ran past a horse.',
      '"Catch me!" he called.',
      '',
      'They all chased him but couldn\'t catch him.',
      '',
      'He came to a river.',
      'A fox offered to help him cross.',
      '',
      'The Gingerbread Man jumped on the fox\'s back.',
      'The fox swam across the river.',
      '',
      'Halfway across, the fox tossed the Gingerbread Man up.',
      'And ate him!',
      '',
      'The moral: Don\'t trust strangers too easily.'
    ],
    level: 2,
    category: 'story',
    tags: ['姜饼', '逃跑', '童话'],
    bgGradient: 'from-orange-100 via-amber-100 to-yellow-100',
    icon: '🍪'
  },
  {
    id: 'little-red-hen',
    title: 'The Little Red Hen',
    titleCn: '小红母鸡',
    content: [
      'The Little Red Hen found some wheat.',
      '"Who will help me plant this?" she asked.',
      '',
      '"Not I," said the cat.',
      '"Not I," said the dog.',
      '"Not I," said the pig.',
      '',
      'So the Little Red Hen planted it herself.',
      '',
      '"Who will help me cut the wheat?" she asked.',
      '"Not I," said the cat.',
      '"Not I," said the dog.',
      '"Not I," said the pig.',
      '',
      'So the Little Red Hen cut it herself.',
      '',
      '"Who will help me make the flour?" she asked.',
      '"Not I," said the cat.',
      '"Not I," said the dog.',
      '"Not I," said the pig.',
      '',
      'So the Little Red Hen made the flour herself.',
      '',
      'She baked delicious bread.',
      '"Who will help me eat this?" she asked.',
      '',
      '"I will!" said the cat.',
      '"I will!" said the dog.',
      '"I will!" said the pig.',
      '',
      '"No!" said the Little Red Hen.',
      '"I will eat it all myself."',
      '',
      'The moral: If you don\'t work, you don\'t eat.'
    ],
    level: 2,
    category: 'story',
    tags: ['鸡', '工作', '寓言'],
    bgGradient: 'from-red-100 via-orange-100 to-yellow-100',
    icon: '🐔'
  },
  {
    id: 'chicken-little',
    title: 'Chicken Little',
    titleCn: '小鸡利特',
    content: [
      'Chicken Little was in the woods.',
      'An acorn fell on her head.',
      '',
      '"The sky is falling!" she cried.',
      '"I must tell the king!"',
      '',
      'She met Henny Penny.',
      '"Where are you going?" asked Henny Penny.',
      '"The sky is falling! Come with me!"',
      '',
      'They met Ducky Lucky.',
      '"The sky is falling! Come with us!"',
      '',
      'They met Foxy Loxy.',
      '"Where are you going?" asked Foxy Loxy.',
      '"The sky is falling! We\'re going to tell the king!"',
      '',
      '"I know a shortcut," said Foxy Loxy.',
      'He led them to his cave.',
      '',
      'But Chicken Little saw feathers on the ground.',
      'She realized Foxy Loxy was tricking them!',
      '',
      '"Run!" she cried.',
      'They escaped just in time.',
      '',
      'The moral: Think before you act.'
    ],
    level: 2,
    category: 'story',
    tags: ['恐慌', '狐狸', '寓言'],
    bgGradient: 'from-orange-100 via-red-100 to-pink-100',
    icon: '🐔'
  },
  {
    id: 'stone-soup',
    title: 'Stone Soup',
    titleCn: '石头汤',
    content: [
      'A traveler came to a poor village.',
      'The people were hungry and selfish.',
      '',
      'The traveler had nothing but a pot and a stone.',
      'He put water and the stone in the pot.',
      '',
      '"I\'m making stone soup," he said.',
      '"It\'s delicious!"',
      '',
      'One woman watched.',
      '"It would taste better with some carrots," she said.',
      'She gave him some carrots.',
      '',
      'A man watched.',
      '"It would taste better with some potatoes," he said.',
      'He gave him some potatoes.',
      '',
      'Everyone gave something.',
      'Onions, meat, herbs, and more.',
      '',
      'The soup smelled wonderful.',
      'Everyone ate together.',
      '',
      '"This is the best soup I ever had!" said one woman.',
      '"And it started with just a stone!"',
      '',
      'The moral: When we share, we all have more.'
    ],
    level: 3,
    category: 'story',
    tags: ['分享', '社区', '智慧'],
    bgGradient: 'from-amber-100 via-yellow-100 to-orange-100',
    icon: '🍲'
  },
  {
    id: 'miller-daughter',
    title: 'Rumpelstiltskin',
    titleCn: '伦佩尔施蒂尔茨金',
    content: [
      'A miller boasted that his daughter could spin straw into gold.',
      'The king heard and locked her in a room.',
      '',
      '"Spin this straw into gold by morning, or you will die."',
      '',
      'The girl cried.',
      'A little man appeared.',
      '"I will help you if you give me your necklace."',
      '',
      'He spun the straw into gold.',
      'The king was happy but wanted more gold.',
      '',
      'The little man helped again for her ring.',
      'The third time, she had nothing to give.',
      '',
      '"Give me your first child," he said.',
      'She agreed, and he spun the gold.',
      '',
      'The king married her.',
      'When their first child was born, the little man came.',
      '',
      '"Guess my name in three days, and you keep the child."',
      '',
      'The queen searched everywhere.',
      'Finally, she heard him singing his name in the forest.',
      '"Rumpelstiltskin! Rumpelstiltskin!"',
      '',
      '"How did you know?" he cried angrily.',
      'He ran away and never came back.'
    ],
    level: 4,
    category: 'story',
    tags: ['魔法', '谜题', '童话'],
    bgGradient: 'from-purple-100 via-indigo-100 to-blue-100',
    icon: '🧙‍♂️'
  },
  {
    id: 'jack-beanstalk',
    title: 'Jack and the Beanstalk',
    titleCn: '杰克与豆茎',
    content: [
      'Jack and his mother were very poor.',
      'Their only cow gave no more milk.',
      '',
      'Jack sold the cow for five magic beans.',
      'His mother was angry and threw them out the window.',
      '',
      'Overnight, a giant beanstalk grew to the sky!',
      'Jack climbed it.',
      '',
      'He found a castle in the clouds.',
      'A giant lived there!',
      '',
      'The giant\'s wife was kind and fed Jack.',
      'But when the giant came, she hid Jack.',
      '',
      'Jack heard the giant counting his gold coins.',
      '"Fee-fi-fo-fum, I smell the blood of an Englishman!"',
      '',
      'Jack waited until the giant fell asleep.',
      'He stole a bag of gold and ran down the beanstalk.',
      '',
      'Jack climbed up again and stole a hen that laid golden eggs.',
      'He climbed up a third time and stole a golden harp.',
      '',
      'The harp called out! The giant chased Jack.',
      'Jack slid down the beanstalk and chopped it down.',
      'The giant fell and was never seen again.',
      '',
      'Jack and his mother lived happily ever after.'
    ],
    level: 3,
    category: 'story',
    tags: ['巨人', '豆茎', '冒险'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🌱'
  },
  {
    id: 'elves-shoemaker',
    title: 'The Elves and the Shoemaker',
    titleCn: ' elves和鞋匠',
    content: [
      'A poor shoemaker had only enough leather for one pair of shoes.',
      'He cut the leather and went to bed.',
      '',
      'In the morning, he found beautiful finished shoes!',
      'Someone had made them while he slept.',
      '',
      'A customer bought them for a high price.',
      'Now the shoemaker could buy leather for two pairs.',
      '',
      'Again, he cut the leather and went to bed.',
      'In the morning, two pairs of beautiful shoes were done!',
      '',
      'This happened every night.',
      'The shoemaker became rich and famous.',
      '',
      'One Christmas Eve, the shoemaker and his wife stayed up.',
      'They saw two little elves making shoes.',
      '',
      'The elves wore old clothes.',
      'The wife made them beautiful new clothes.',
      '',
      'The next night, the elves found the clothes.',
      'They danced happily and disappeared.',
      '',
      'The shoemaker never saw them again.',
      'But he always remembered their kindness.'
    ],
    level: 3,
    category: 'story',
    tags: ['精灵', '善良', '童话'],
    bgGradient: 'from-amber-100 via-orange-100 to-yellow-100',
    icon: '👞'
  },
  {
    id: 'princess-pea',
    title: 'The Princess and the Pea',
    titleCn: '豌豆公主',
    content: [
      'A prince wanted to marry a real princess.',
      'He traveled everywhere but could not find one.',
      '',
      'One stormy night, a princess arrived at the castle.',
      'She was wet and tired.',
      '',
      'The queen was not sure she was a real princess.',
      'She put a pea under twenty mattresses.',
      '',
      '"Only a real princess would feel it," she thought.',
      '',
      'The princess slept on the bed.',
      'In the morning, she had bruises.',
      '',
      '"I slept terribly!" she said.',
      '"There was something hard in the bed!"',
      '',
      'The queen knew she was a real princess.',
      'The prince was overjoyed.',
      '',
      'They got married and lived happily.',
      'The pea was put in a museum.',
      '',
      'The moral: True sensitivity is rare.'
    ],
    level: 3,
    category: 'story',
    tags: ['公主', '豌豆', '童话'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '👑'
  },
  {
    id: 'wild-swans',
    title: 'The Wild Swans',
    titleCn: '野天鹅',
    content: [
      'A king had eleven sons and one daughter, Elisa.',
      'The queen died, and the king remarried.',
      '',
      'The wicked stepmother turned the sons into swans.',
      'She sent Elisa away.',
      '',
      'Elisa found her brothers in the forest.',
      'They were swans by day but humans by night.',
      '',
      '"We can be saved," they said.',
      '"You must knit us shirts of nettles.',
      'And you cannot speak until they are done."',
      '',
      'Elisa worked day and night.',
      'Her hands were bleeding.',
      '',
      'A king saw her and fell in love.',
      'They married, but she could not speak.',
      '',
      'The archbishop accused her of witchcraft.',
      'She was going to be burned.',
      '',
      'Just then, the eleven swans flew down.',
      'She threw the shirts over them.',
      '',
      'They turned back into princes!',
      'But one shirt was not finished, so one brother still had a wing.',
      '',
      'The king knew she was innocent.',
      'They lived happily ever after.'
    ],
    level: 5,
    category: 'story',
    tags: ['天鹅', '姐妹', '童话'],
    bgGradient: 'from-blue-100 via-cyan-100 to-teal-100',
    icon: '🦢'
  },
  {
    id: 'nightingale',
    title: 'The Nightingale',
    titleCn: '夜莺',
    content: [
      'In China, there lived a nightingale with a beautiful voice.',
      'The Emperor heard about her.',
      '',
      'He wanted her to sing for him.',
      'She sang and everyone was moved.',
      '',
      'The Emperor kept her in a cage.',
      'But she was sad and sang less.',
      '',
      'The Emperor received a mechanical nightingale as a gift.',
      'It was beautiful with jewels.',
      'It sang perfectly.',
      '',
      'The Emperor preferred the mechanical bird.',
      'The real nightingale flew away.',
      '',
      'Years later, the Emperor was sick.',
      'Death stood beside him.',
      'The mechanical bird stopped working.',
      '',
      'Suddenly, the real nightingale sang outside.',
      'Death was moved by her song and left.',
      '',
      'The Emperor recovered.',
      'He freed the mechanical nightingale.',
      'He let the real nightingale sing freely.',
      '',
      'The nightingale became his friend and sang for him forever.'
    ],
    level: 4,
    category: 'story',
    tags: ['鸟', '音乐', '童话'],
    bgGradient: 'from-indigo-100 via-purple-100 to-pink-100',
    icon: '🐦'
  },
  {
    id: 'happy-prince',
    title: 'The Happy Prince',
    titleCn: '快乐王子',
    content: [
      'The statue of the Happy Prince stood high above the city.',
      'He was covered with gold and had jewel eyes.',
      '',
      'A little swallow stayed with him on his journey south.',
      '',
      '"Take my ruby eye to a sick boy," said the Prince.',
      'The swallow did.',
      '',
      '"Take my sapphire eye to a poor writer," said the Prince.',
      'The swallow did.',
      '',
      '"Take my gold to the poor children," said the Prince.',
      'The swallow stripped the statue bare.',
      '',
      'Winter came and the swallow could not leave.',
      'He died of cold at the Prince\'s feet.',
      '',
      'The Prince\'s heart broke when the swallow died.',
      '',
      'The people wanted to tear down the ugly statue.',
      'But God\'s angels chose the lead heart and the dead bird.',
      '',
      '"They are the most precious things in the city," God said.',
      '',
      'The moral: True beauty is found in kindness and sacrifice.'
    ],
    level: 5,
    category: 'story',
    tags: ['牺牲', '慈善', '童话'],
    bgGradient: 'from-yellow-100 via-amber-100 to-orange-100',
    icon: '🕊️'
  },
  {
    id: 'selfish-giant',
    title: 'The Selfish Giant',
    titleCn: '自私的巨人',
    content: [
      'A giant had a beautiful garden.',
      'Children loved to play there.',
      '',
      'The giant was away for seven years.',
      'When he returned, he was angry.',
      '',
      '"My garden is mine!" he shouted.',
      'He built a wall around it.',
      '',
      'Spring came, but the giant\'s garden stayed winter.',
      'Only the north wind and frost played there.',
      '',
      'The giant was sad.',
      'One morning, he heard music.',
      'The children had found a hole in the wall.',
      '',
      'Where the children were, flowers bloomed.',
      'In other parts of the garden, it was still winter.',
      '',
      'The giant helped one little boy climb a tree.',
      'He saw the boy\'s wounds and was angry.',
      '',
      '"Who hurt you?" he asked.',
      '"These are the wounds of Love," said the boy.',
      '',
      'The giant broke down the wall.',
      'Children played in his garden every day.',
      '',
      'Years later, the giant died peacefully.',
      'The little boy was an angel, taking him to paradise.'
    ],
    level: 5,
    category: 'story',
    tags: ['自私', '爱', '童话'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🌳'
  },
  {
    id: 'velveteen-rabbit',
    title: 'The Velveteen Rabbit',
    titleCn: '天鹅绒兔子',
    content: [
      'A boy received a velveteen rabbit for Christmas.',
      'At first, he preferred his other toys.',
      '',
      'The Skin Horse told the rabbit about becoming real.',
      '"When a child really loves you for a long time, you become real."',
      '',
      'The rabbit wanted to be real.',
      'One day, the boy lost his favorite toy.',
      'He started sleeping with the velveteen rabbit.',
      '',
      'The rabbit became ragged from so much love.',
      'But he was happy.',
      '',
      'The boy got scarlet fever.',
      'All his toys had to be burned.',
      '',
      'The rabbit was thrown into a sack to be burned.',
      'He cried a real tear.',
      '',
      'A flower fairy appeared.',
      'She turned him into a real rabbit!',
      '',
      'In the spring, the rabbit saw the boy.',
      'The boy saw a real rabbit that looked like his old toy.',
      '',
      'The rabbit hopped away, knowing he was real at last.'
    ],
    level: 4,
    category: 'story',
    tags: ['玩具', '爱', '成长'],
    bgGradient: 'from-pink-100 via-rose-100 to-red-100',
    icon: '🐰'
  },
  {
    id: 'secret-garden',
    title: 'The Secret Garden',
    titleCn: '秘密花园',
    content: [
      'Mary Lennox was sent to live with her uncle in England.',
      'She was sickly and bad-tempered.',
      '',
      'She found a key to a secret garden.',
      'The garden had been locked for ten years.',
      '',
      'She met Dickon, a boy who could talk to animals.',
      'They worked together to restore the garden.',
      '',
      'Mary heard crying in the house.',
      'She found her cousin Colin, who was sickly too.',
      '',
      'Colin believed he would never walk.',
      'He was afraid of the future.',
      '',
      'Mary and Dickon took Colin to the secret garden.',
      'The fresh air and sunshine made him stronger.',
      '',
      'Colin learned to walk!',
      'He ran in the garden and laughed.',
      '',
      'Mary became healthy and happy too.',
      'They all grew strong in the secret garden.',
      '',
      'The father came home and found the children.',
      'He was overjoyed to see his son healthy.',
      '',
      'The garden brought healing to everyone.',
      '',
      'The moral: Nature and love can heal the soul.'
    ],
    level: 5,
    category: 'story',
    tags: ['花园', '治愈', '成长'],
    bgGradient: 'from-green-100 via-emerald-100 to-teal-100',
    icon: '🌹'
  },
  {
    id: 'winnie-pooh',
    title: 'Winnie the Pooh',
    titleCn: '小熊维尼',
    content: [
      'In the Hundred Acre Wood lived Winnie the Pooh.',
      'He was a bear of very little brain but a big heart.',
      '',
      'His best friend was Christopher Robin.',
      'He also had many other friends.',
      '',
      'Piglet was very small but very brave.',
      'Tigger loved to bounce.',
      'Eeyore was always sad but very kind.',
      '',
      'Rabbit was very practical and organized.',
      'Owl was very wise.',
      'Kanga and Roo were a loving mother and son.',
      '',
      'One day, Pooh ran out of honey.',
      'He went to visit Rabbit.',
      'He ate so much that he got stuck in Rabbit\'s door!',
      '',
      'Christopher Robin came and helped.',
      'They had to wait a week for Pooh to get thin enough.',
      '',
      'Pooh learned a lesson.',
      '"You can\'t stay in Rabbit\'s house forever," he said.',
      '"You have to come out sometime."',
      '',
      'And so they all lived happily in the Hundred Acre Wood.',
      'Having adventures and eating honey.'
    ],
    level: 3,
    category: 'story',
    tags: ['熊', '友谊', '童话'],
    bgGradient: 'from-yellow-100 via-amber-100 to-orange-100',
    icon: '🍯'
  },
  {
    id: 'charlie-chocolate',
    title: 'Charlie and the Chocolate Factory',
    titleCn: '查理和巧克力工厂',
    content: [
      'Charlie Bucket was very poor.',
      'He lived with his parents and grandparents.',
      'They were very hungry.',
      '',
      'Nearby was Willy Wonka\'s chocolate factory.',
      'It was the most wonderful place in the world.',
      '',
      'Mr. Wonka announced a contest.',
      'Five children who found golden tickets could visit the factory.',
      '',
      'Charlie found a golden ticket!',
      'The other winners were Augustus, Veruca, Violet, and Mike.',
      '',
      'In the factory, everything was magical.',
      'Chocolate waterfalls, edible grass, and candies of all kinds.',
      '',
      'Augustus fell into the chocolate river.',
      'Veruca wanted everything and fell into a garbage chute.',
      'Violet ate experimental gum and turned into a blueberry.',
      'Mike was shrunk by a television machine.',
      '',
      'Only Charlie remained.',
      'Mr. Wonka liked Charlie\'s kindness.',
      '',
      '"You can have the factory!" said Mr. Wonka.',
      '"Your whole family can live here with you."',
      '',
      'Charlie and his family moved into the factory.',
      'They lived happily ever after, eating chocolate every day.'
    ],
    level: 4,
    category: 'story',
    tags: ['巧克力', '工厂', '冒险'],
    bgGradient: 'from-amber-100 via-yellow-100 to-orange-100',
    icon: '🍫'
  },
  {
    id: 'matilda',
    title: 'Matilda',
    titleCn: '玛蒂尔达',
    content: [
      'Matilda was a little girl with extraordinary powers.',
      'She could read books and do math by age four.',
      '',
      'Her parents did not care about her.',
      'Her headmistress, Miss Trunchbull, was cruel.',
      '',
      'But Matilda found a friend in Miss Honey.',
      'Her teacher was kind and gentle.',
      '',
      'Miss Trunchbull treated everyone badly.',
      'She hated children.',
      '',
      'One day, Matilda discovered she could move things with her mind.',
      'She used her powers to help Miss Honey.',
      '',
      'Miss Trunchbull had taken Miss Honey\'s house.',
      'Matilda scared her away with magic chalk writing.',
      '',
      'Miss Trunchbull ran away forever.',
      'Miss Honey got her house back.',
      '',
      'Matilda\'s parents decided to move away.',
      'But Matilda wanted to stay with Miss Honey.',
      '',
      'Her parents agreed, and Matilda lived with Miss Honey.',
      'She went to a better school and used her powers for good.'
    ],
    level: 4,
    category: 'story',
    tags: ['魔法', '学校', '成长'],
    bgGradient: 'from-pink-100 via-purple-100 to-blue-100',
    icon: '📚'
  }
];
